# syntax=docker/dockerfile:1

FROM node:22-slim AS builder
WORKDIR /app

COPY package*.json ./
COPY apps/http/query/package*.json ./apps/http/query/
COPY packages/package*.json ./packages/
RUN npm ci

COPY . .
RUN npm run -w @baseball/query build

FROM node:22-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8080

COPY package*.json ./
COPY apps/http/query/package*.json ./apps/http/query/
COPY packages/package*.json ./packages/
RUN npm ci --omit=dev

COPY --from=builder /app/apps/http/query/dist ./dist
CMD ["node", "dist/apps/http/query/src/main.js"]