
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BallParkDailyWeatherForecast` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model BallParkDailyWeatherForecast
 * 
 */
export type BallParkDailyWeatherForecastModel = runtime.Types.Result.DefaultSelection<Prisma.$BallParkDailyWeatherForecastPayload>

export type AggregateBallParkDailyWeatherForecast = {
  _count: BallParkDailyWeatherForecastCountAggregateOutputType | null
  _avg: BallParkDailyWeatherForecastAvgAggregateOutputType | null
  _sum: BallParkDailyWeatherForecastSumAggregateOutputType | null
  _min: BallParkDailyWeatherForecastMinAggregateOutputType | null
  _max: BallParkDailyWeatherForecastMaxAggregateOutputType | null
}

export type BallParkDailyWeatherForecastAvgAggregateOutputType = {
  id: number | null
  weatherCode: number | null
  temperatureMin: number | null
  temperatureMax: number | null
  precipitationProbability: number | null
  rainFall: number | null
  ballParkId: number | null
}

export type BallParkDailyWeatherForecastSumAggregateOutputType = {
  id: number | null
  weatherCode: number | null
  temperatureMin: number | null
  temperatureMax: number | null
  precipitationProbability: number | null
  rainFall: number | null
  ballParkId: number | null
}

export type BallParkDailyWeatherForecastMinAggregateOutputType = {
  id: number | null
  date: Date | null
  weatherCode: number | null
  temperatureMin: number | null
  temperatureMax: number | null
  precipitationProbability: number | null
  rainFall: number | null
  ballParkId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BallParkDailyWeatherForecastMaxAggregateOutputType = {
  id: number | null
  date: Date | null
  weatherCode: number | null
  temperatureMin: number | null
  temperatureMax: number | null
  precipitationProbability: number | null
  rainFall: number | null
  ballParkId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BallParkDailyWeatherForecastCountAggregateOutputType = {
  id: number
  date: number
  weatherCode: number
  temperatureMin: number
  temperatureMax: number
  precipitationProbability: number
  rainFall: number
  ballParkId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type BallParkDailyWeatherForecastAvgAggregateInputType = {
  id?: true
  weatherCode?: true
  temperatureMin?: true
  temperatureMax?: true
  precipitationProbability?: true
  rainFall?: true
  ballParkId?: true
}

export type BallParkDailyWeatherForecastSumAggregateInputType = {
  id?: true
  weatherCode?: true
  temperatureMin?: true
  temperatureMax?: true
  precipitationProbability?: true
  rainFall?: true
  ballParkId?: true
}

export type BallParkDailyWeatherForecastMinAggregateInputType = {
  id?: true
  date?: true
  weatherCode?: true
  temperatureMin?: true
  temperatureMax?: true
  precipitationProbability?: true
  rainFall?: true
  ballParkId?: true
  createdAt?: true
  updatedAt?: true
}

export type BallParkDailyWeatherForecastMaxAggregateInputType = {
  id?: true
  date?: true
  weatherCode?: true
  temperatureMin?: true
  temperatureMax?: true
  precipitationProbability?: true
  rainFall?: true
  ballParkId?: true
  createdAt?: true
  updatedAt?: true
}

export type BallParkDailyWeatherForecastCountAggregateInputType = {
  id?: true
  date?: true
  weatherCode?: true
  temperatureMin?: true
  temperatureMax?: true
  precipitationProbability?: true
  rainFall?: true
  ballParkId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type BallParkDailyWeatherForecastAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BallParkDailyWeatherForecast to aggregate.
   */
  where?: Prisma.BallParkDailyWeatherForecastWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BallParkDailyWeatherForecasts to fetch.
   */
  orderBy?: Prisma.BallParkDailyWeatherForecastOrderByWithRelationInput | Prisma.BallParkDailyWeatherForecastOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BallParkDailyWeatherForecastWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BallParkDailyWeatherForecasts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BallParkDailyWeatherForecasts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BallParkDailyWeatherForecasts
  **/
  _count?: true | BallParkDailyWeatherForecastCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BallParkDailyWeatherForecastAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BallParkDailyWeatherForecastSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BallParkDailyWeatherForecastMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BallParkDailyWeatherForecastMaxAggregateInputType
}

export type GetBallParkDailyWeatherForecastAggregateType<T extends BallParkDailyWeatherForecastAggregateArgs> = {
      [P in keyof T & keyof AggregateBallParkDailyWeatherForecast]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBallParkDailyWeatherForecast[P]>
    : Prisma.GetScalarType<T[P], AggregateBallParkDailyWeatherForecast[P]>
}




export type BallParkDailyWeatherForecastGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BallParkDailyWeatherForecastWhereInput
  orderBy?: Prisma.BallParkDailyWeatherForecastOrderByWithAggregationInput | Prisma.BallParkDailyWeatherForecastOrderByWithAggregationInput[]
  by: Prisma.BallParkDailyWeatherForecastScalarFieldEnum[] | Prisma.BallParkDailyWeatherForecastScalarFieldEnum
  having?: Prisma.BallParkDailyWeatherForecastScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BallParkDailyWeatherForecastCountAggregateInputType | true
  _avg?: BallParkDailyWeatherForecastAvgAggregateInputType
  _sum?: BallParkDailyWeatherForecastSumAggregateInputType
  _min?: BallParkDailyWeatherForecastMinAggregateInputType
  _max?: BallParkDailyWeatherForecastMaxAggregateInputType
}

export type BallParkDailyWeatherForecastGroupByOutputType = {
  id: number
  date: Date
  weatherCode: number
  temperatureMin: number
  temperatureMax: number
  precipitationProbability: number
  rainFall: number
  ballParkId: number
  createdAt: Date
  updatedAt: Date
  _count: BallParkDailyWeatherForecastCountAggregateOutputType | null
  _avg: BallParkDailyWeatherForecastAvgAggregateOutputType | null
  _sum: BallParkDailyWeatherForecastSumAggregateOutputType | null
  _min: BallParkDailyWeatherForecastMinAggregateOutputType | null
  _max: BallParkDailyWeatherForecastMaxAggregateOutputType | null
}

type GetBallParkDailyWeatherForecastGroupByPayload<T extends BallParkDailyWeatherForecastGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BallParkDailyWeatherForecastGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BallParkDailyWeatherForecastGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BallParkDailyWeatherForecastGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BallParkDailyWeatherForecastGroupByOutputType[P]>
      }
    >
  >



export type BallParkDailyWeatherForecastWhereInput = {
  AND?: Prisma.BallParkDailyWeatherForecastWhereInput | Prisma.BallParkDailyWeatherForecastWhereInput[]
  OR?: Prisma.BallParkDailyWeatherForecastWhereInput[]
  NOT?: Prisma.BallParkDailyWeatherForecastWhereInput | Prisma.BallParkDailyWeatherForecastWhereInput[]
  id?: Prisma.IntFilter<"BallParkDailyWeatherForecast"> | number
  date?: Prisma.DateTimeFilter<"BallParkDailyWeatherForecast"> | Date | string
  weatherCode?: Prisma.IntFilter<"BallParkDailyWeatherForecast"> | number
  temperatureMin?: Prisma.FloatFilter<"BallParkDailyWeatherForecast"> | number
  temperatureMax?: Prisma.FloatFilter<"BallParkDailyWeatherForecast"> | number
  precipitationProbability?: Prisma.FloatFilter<"BallParkDailyWeatherForecast"> | number
  rainFall?: Prisma.FloatFilter<"BallParkDailyWeatherForecast"> | number
  ballParkId?: Prisma.IntFilter<"BallParkDailyWeatherForecast"> | number
  createdAt?: Prisma.DateTimeFilter<"BallParkDailyWeatherForecast"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BallParkDailyWeatherForecast"> | Date | string
}

export type BallParkDailyWeatherForecastOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  weatherCode?: Prisma.SortOrder
  temperatureMin?: Prisma.SortOrder
  temperatureMax?: Prisma.SortOrder
  precipitationProbability?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BallParkDailyWeatherForecastWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  ballParkId_date?: Prisma.BallParkDailyWeatherForecastBallParkIdDateCompoundUniqueInput
  AND?: Prisma.BallParkDailyWeatherForecastWhereInput | Prisma.BallParkDailyWeatherForecastWhereInput[]
  OR?: Prisma.BallParkDailyWeatherForecastWhereInput[]
  NOT?: Prisma.BallParkDailyWeatherForecastWhereInput | Prisma.BallParkDailyWeatherForecastWhereInput[]
  date?: Prisma.DateTimeFilter<"BallParkDailyWeatherForecast"> | Date | string
  weatherCode?: Prisma.IntFilter<"BallParkDailyWeatherForecast"> | number
  temperatureMin?: Prisma.FloatFilter<"BallParkDailyWeatherForecast"> | number
  temperatureMax?: Prisma.FloatFilter<"BallParkDailyWeatherForecast"> | number
  precipitationProbability?: Prisma.FloatFilter<"BallParkDailyWeatherForecast"> | number
  rainFall?: Prisma.FloatFilter<"BallParkDailyWeatherForecast"> | number
  ballParkId?: Prisma.IntFilter<"BallParkDailyWeatherForecast"> | number
  createdAt?: Prisma.DateTimeFilter<"BallParkDailyWeatherForecast"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BallParkDailyWeatherForecast"> | Date | string
}, "id" | "ballParkId_date">

export type BallParkDailyWeatherForecastOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  weatherCode?: Prisma.SortOrder
  temperatureMin?: Prisma.SortOrder
  temperatureMax?: Prisma.SortOrder
  precipitationProbability?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.BallParkDailyWeatherForecastCountOrderByAggregateInput
  _avg?: Prisma.BallParkDailyWeatherForecastAvgOrderByAggregateInput
  _max?: Prisma.BallParkDailyWeatherForecastMaxOrderByAggregateInput
  _min?: Prisma.BallParkDailyWeatherForecastMinOrderByAggregateInput
  _sum?: Prisma.BallParkDailyWeatherForecastSumOrderByAggregateInput
}

export type BallParkDailyWeatherForecastScalarWhereWithAggregatesInput = {
  AND?: Prisma.BallParkDailyWeatherForecastScalarWhereWithAggregatesInput | Prisma.BallParkDailyWeatherForecastScalarWhereWithAggregatesInput[]
  OR?: Prisma.BallParkDailyWeatherForecastScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BallParkDailyWeatherForecastScalarWhereWithAggregatesInput | Prisma.BallParkDailyWeatherForecastScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"BallParkDailyWeatherForecast"> | number
  date?: Prisma.DateTimeWithAggregatesFilter<"BallParkDailyWeatherForecast"> | Date | string
  weatherCode?: Prisma.IntWithAggregatesFilter<"BallParkDailyWeatherForecast"> | number
  temperatureMin?: Prisma.FloatWithAggregatesFilter<"BallParkDailyWeatherForecast"> | number
  temperatureMax?: Prisma.FloatWithAggregatesFilter<"BallParkDailyWeatherForecast"> | number
  precipitationProbability?: Prisma.FloatWithAggregatesFilter<"BallParkDailyWeatherForecast"> | number
  rainFall?: Prisma.FloatWithAggregatesFilter<"BallParkDailyWeatherForecast"> | number
  ballParkId?: Prisma.IntWithAggregatesFilter<"BallParkDailyWeatherForecast"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BallParkDailyWeatherForecast"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BallParkDailyWeatherForecast"> | Date | string
}

export type BallParkDailyWeatherForecastCreateInput = {
  date: Date | string
  weatherCode: number
  temperatureMin: number
  temperatureMax: number
  precipitationProbability: number
  rainFall: number
  ballParkId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BallParkDailyWeatherForecastUncheckedCreateInput = {
  id?: number
  date: Date | string
  weatherCode: number
  temperatureMin: number
  temperatureMax: number
  precipitationProbability: number
  rainFall: number
  ballParkId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BallParkDailyWeatherForecastUpdateInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weatherCode?: Prisma.IntFieldUpdateOperationsInput | number
  temperatureMin?: Prisma.FloatFieldUpdateOperationsInput | number
  temperatureMax?: Prisma.FloatFieldUpdateOperationsInput | number
  precipitationProbability?: Prisma.FloatFieldUpdateOperationsInput | number
  rainFall?: Prisma.FloatFieldUpdateOperationsInput | number
  ballParkId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BallParkDailyWeatherForecastUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weatherCode?: Prisma.IntFieldUpdateOperationsInput | number
  temperatureMin?: Prisma.FloatFieldUpdateOperationsInput | number
  temperatureMax?: Prisma.FloatFieldUpdateOperationsInput | number
  precipitationProbability?: Prisma.FloatFieldUpdateOperationsInput | number
  rainFall?: Prisma.FloatFieldUpdateOperationsInput | number
  ballParkId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BallParkDailyWeatherForecastCreateManyInput = {
  id?: number
  date: Date | string
  weatherCode: number
  temperatureMin: number
  temperatureMax: number
  precipitationProbability: number
  rainFall: number
  ballParkId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BallParkDailyWeatherForecastUpdateManyMutationInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weatherCode?: Prisma.IntFieldUpdateOperationsInput | number
  temperatureMin?: Prisma.FloatFieldUpdateOperationsInput | number
  temperatureMax?: Prisma.FloatFieldUpdateOperationsInput | number
  precipitationProbability?: Prisma.FloatFieldUpdateOperationsInput | number
  rainFall?: Prisma.FloatFieldUpdateOperationsInput | number
  ballParkId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BallParkDailyWeatherForecastUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weatherCode?: Prisma.IntFieldUpdateOperationsInput | number
  temperatureMin?: Prisma.FloatFieldUpdateOperationsInput | number
  temperatureMax?: Prisma.FloatFieldUpdateOperationsInput | number
  precipitationProbability?: Prisma.FloatFieldUpdateOperationsInput | number
  rainFall?: Prisma.FloatFieldUpdateOperationsInput | number
  ballParkId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BallParkDailyWeatherForecastBallParkIdDateCompoundUniqueInput = {
  ballParkId: number
  date: Date | string
}

export type BallParkDailyWeatherForecastCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  weatherCode?: Prisma.SortOrder
  temperatureMin?: Prisma.SortOrder
  temperatureMax?: Prisma.SortOrder
  precipitationProbability?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BallParkDailyWeatherForecastAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  weatherCode?: Prisma.SortOrder
  temperatureMin?: Prisma.SortOrder
  temperatureMax?: Prisma.SortOrder
  precipitationProbability?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
}

export type BallParkDailyWeatherForecastMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  weatherCode?: Prisma.SortOrder
  temperatureMin?: Prisma.SortOrder
  temperatureMax?: Prisma.SortOrder
  precipitationProbability?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BallParkDailyWeatherForecastMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  weatherCode?: Prisma.SortOrder
  temperatureMin?: Prisma.SortOrder
  temperatureMax?: Prisma.SortOrder
  precipitationProbability?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BallParkDailyWeatherForecastSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  weatherCode?: Prisma.SortOrder
  temperatureMin?: Prisma.SortOrder
  temperatureMax?: Prisma.SortOrder
  precipitationProbability?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
}



export type BallParkDailyWeatherForecastSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  weatherCode?: boolean
  temperatureMin?: boolean
  temperatureMax?: boolean
  precipitationProbability?: boolean
  rainFall?: boolean
  ballParkId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["ballParkDailyWeatherForecast"]>



export type BallParkDailyWeatherForecastSelectScalar = {
  id?: boolean
  date?: boolean
  weatherCode?: boolean
  temperatureMin?: boolean
  temperatureMax?: boolean
  precipitationProbability?: boolean
  rainFall?: boolean
  ballParkId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type BallParkDailyWeatherForecastOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "weatherCode" | "temperatureMin" | "temperatureMax" | "precipitationProbability" | "rainFall" | "ballParkId" | "createdAt" | "updatedAt", ExtArgs["result"]["ballParkDailyWeatherForecast"]>

export type $BallParkDailyWeatherForecastPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BallParkDailyWeatherForecast"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    date: Date
    weatherCode: number
    temperatureMin: number
    temperatureMax: number
    precipitationProbability: number
    rainFall: number
    ballParkId: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["ballParkDailyWeatherForecast"]>
  composites: {}
}

export type BallParkDailyWeatherForecastGetPayload<S extends boolean | null | undefined | BallParkDailyWeatherForecastDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BallParkDailyWeatherForecastPayload, S>

export type BallParkDailyWeatherForecastCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BallParkDailyWeatherForecastFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BallParkDailyWeatherForecastCountAggregateInputType | true
  }

export interface BallParkDailyWeatherForecastDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BallParkDailyWeatherForecast'], meta: { name: 'BallParkDailyWeatherForecast' } }
  /**
   * Find zero or one BallParkDailyWeatherForecast that matches the filter.
   * @param {BallParkDailyWeatherForecastFindUniqueArgs} args - Arguments to find a BallParkDailyWeatherForecast
   * @example
   * // Get one BallParkDailyWeatherForecast
   * const ballParkDailyWeatherForecast = await prisma.ballParkDailyWeatherForecast.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BallParkDailyWeatherForecastFindUniqueArgs>(args: Prisma.SelectSubset<T, BallParkDailyWeatherForecastFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BallParkDailyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkDailyWeatherForecastPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BallParkDailyWeatherForecast that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BallParkDailyWeatherForecastFindUniqueOrThrowArgs} args - Arguments to find a BallParkDailyWeatherForecast
   * @example
   * // Get one BallParkDailyWeatherForecast
   * const ballParkDailyWeatherForecast = await prisma.ballParkDailyWeatherForecast.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BallParkDailyWeatherForecastFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BallParkDailyWeatherForecastFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BallParkDailyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkDailyWeatherForecastPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BallParkDailyWeatherForecast that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkDailyWeatherForecastFindFirstArgs} args - Arguments to find a BallParkDailyWeatherForecast
   * @example
   * // Get one BallParkDailyWeatherForecast
   * const ballParkDailyWeatherForecast = await prisma.ballParkDailyWeatherForecast.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BallParkDailyWeatherForecastFindFirstArgs>(args?: Prisma.SelectSubset<T, BallParkDailyWeatherForecastFindFirstArgs<ExtArgs>>): Prisma.Prisma__BallParkDailyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkDailyWeatherForecastPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BallParkDailyWeatherForecast that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkDailyWeatherForecastFindFirstOrThrowArgs} args - Arguments to find a BallParkDailyWeatherForecast
   * @example
   * // Get one BallParkDailyWeatherForecast
   * const ballParkDailyWeatherForecast = await prisma.ballParkDailyWeatherForecast.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BallParkDailyWeatherForecastFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BallParkDailyWeatherForecastFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BallParkDailyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkDailyWeatherForecastPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BallParkDailyWeatherForecasts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkDailyWeatherForecastFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BallParkDailyWeatherForecasts
   * const ballParkDailyWeatherForecasts = await prisma.ballParkDailyWeatherForecast.findMany()
   * 
   * // Get first 10 BallParkDailyWeatherForecasts
   * const ballParkDailyWeatherForecasts = await prisma.ballParkDailyWeatherForecast.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ballParkDailyWeatherForecastWithIdOnly = await prisma.ballParkDailyWeatherForecast.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BallParkDailyWeatherForecastFindManyArgs>(args?: Prisma.SelectSubset<T, BallParkDailyWeatherForecastFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BallParkDailyWeatherForecastPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BallParkDailyWeatherForecast.
   * @param {BallParkDailyWeatherForecastCreateArgs} args - Arguments to create a BallParkDailyWeatherForecast.
   * @example
   * // Create one BallParkDailyWeatherForecast
   * const BallParkDailyWeatherForecast = await prisma.ballParkDailyWeatherForecast.create({
   *   data: {
   *     // ... data to create a BallParkDailyWeatherForecast
   *   }
   * })
   * 
   */
  create<T extends BallParkDailyWeatherForecastCreateArgs>(args: Prisma.SelectSubset<T, BallParkDailyWeatherForecastCreateArgs<ExtArgs>>): Prisma.Prisma__BallParkDailyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkDailyWeatherForecastPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BallParkDailyWeatherForecasts.
   * @param {BallParkDailyWeatherForecastCreateManyArgs} args - Arguments to create many BallParkDailyWeatherForecasts.
   * @example
   * // Create many BallParkDailyWeatherForecasts
   * const ballParkDailyWeatherForecast = await prisma.ballParkDailyWeatherForecast.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BallParkDailyWeatherForecastCreateManyArgs>(args?: Prisma.SelectSubset<T, BallParkDailyWeatherForecastCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a BallParkDailyWeatherForecast.
   * @param {BallParkDailyWeatherForecastDeleteArgs} args - Arguments to delete one BallParkDailyWeatherForecast.
   * @example
   * // Delete one BallParkDailyWeatherForecast
   * const BallParkDailyWeatherForecast = await prisma.ballParkDailyWeatherForecast.delete({
   *   where: {
   *     // ... filter to delete one BallParkDailyWeatherForecast
   *   }
   * })
   * 
   */
  delete<T extends BallParkDailyWeatherForecastDeleteArgs>(args: Prisma.SelectSubset<T, BallParkDailyWeatherForecastDeleteArgs<ExtArgs>>): Prisma.Prisma__BallParkDailyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkDailyWeatherForecastPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BallParkDailyWeatherForecast.
   * @param {BallParkDailyWeatherForecastUpdateArgs} args - Arguments to update one BallParkDailyWeatherForecast.
   * @example
   * // Update one BallParkDailyWeatherForecast
   * const ballParkDailyWeatherForecast = await prisma.ballParkDailyWeatherForecast.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BallParkDailyWeatherForecastUpdateArgs>(args: Prisma.SelectSubset<T, BallParkDailyWeatherForecastUpdateArgs<ExtArgs>>): Prisma.Prisma__BallParkDailyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkDailyWeatherForecastPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BallParkDailyWeatherForecasts.
   * @param {BallParkDailyWeatherForecastDeleteManyArgs} args - Arguments to filter BallParkDailyWeatherForecasts to delete.
   * @example
   * // Delete a few BallParkDailyWeatherForecasts
   * const { count } = await prisma.ballParkDailyWeatherForecast.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BallParkDailyWeatherForecastDeleteManyArgs>(args?: Prisma.SelectSubset<T, BallParkDailyWeatherForecastDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BallParkDailyWeatherForecasts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkDailyWeatherForecastUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BallParkDailyWeatherForecasts
   * const ballParkDailyWeatherForecast = await prisma.ballParkDailyWeatherForecast.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BallParkDailyWeatherForecastUpdateManyArgs>(args: Prisma.SelectSubset<T, BallParkDailyWeatherForecastUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one BallParkDailyWeatherForecast.
   * @param {BallParkDailyWeatherForecastUpsertArgs} args - Arguments to update or create a BallParkDailyWeatherForecast.
   * @example
   * // Update or create a BallParkDailyWeatherForecast
   * const ballParkDailyWeatherForecast = await prisma.ballParkDailyWeatherForecast.upsert({
   *   create: {
   *     // ... data to create a BallParkDailyWeatherForecast
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BallParkDailyWeatherForecast we want to update
   *   }
   * })
   */
  upsert<T extends BallParkDailyWeatherForecastUpsertArgs>(args: Prisma.SelectSubset<T, BallParkDailyWeatherForecastUpsertArgs<ExtArgs>>): Prisma.Prisma__BallParkDailyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkDailyWeatherForecastPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BallParkDailyWeatherForecasts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkDailyWeatherForecastCountArgs} args - Arguments to filter BallParkDailyWeatherForecasts to count.
   * @example
   * // Count the number of BallParkDailyWeatherForecasts
   * const count = await prisma.ballParkDailyWeatherForecast.count({
   *   where: {
   *     // ... the filter for the BallParkDailyWeatherForecasts we want to count
   *   }
   * })
  **/
  count<T extends BallParkDailyWeatherForecastCountArgs>(
    args?: Prisma.Subset<T, BallParkDailyWeatherForecastCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BallParkDailyWeatherForecastCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BallParkDailyWeatherForecast.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkDailyWeatherForecastAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BallParkDailyWeatherForecastAggregateArgs>(args: Prisma.Subset<T, BallParkDailyWeatherForecastAggregateArgs>): Prisma.PrismaPromise<GetBallParkDailyWeatherForecastAggregateType<T>>

  /**
   * Group by BallParkDailyWeatherForecast.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkDailyWeatherForecastGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BallParkDailyWeatherForecastGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BallParkDailyWeatherForecastGroupByArgs['orderBy'] }
      : { orderBy?: BallParkDailyWeatherForecastGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BallParkDailyWeatherForecastGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBallParkDailyWeatherForecastGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BallParkDailyWeatherForecast model
 */
readonly fields: BallParkDailyWeatherForecastFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BallParkDailyWeatherForecast.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BallParkDailyWeatherForecastClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BallParkDailyWeatherForecast model
 */
export interface BallParkDailyWeatherForecastFieldRefs {
  readonly id: Prisma.FieldRef<"BallParkDailyWeatherForecast", 'Int'>
  readonly date: Prisma.FieldRef<"BallParkDailyWeatherForecast", 'DateTime'>
  readonly weatherCode: Prisma.FieldRef<"BallParkDailyWeatherForecast", 'Int'>
  readonly temperatureMin: Prisma.FieldRef<"BallParkDailyWeatherForecast", 'Float'>
  readonly temperatureMax: Prisma.FieldRef<"BallParkDailyWeatherForecast", 'Float'>
  readonly precipitationProbability: Prisma.FieldRef<"BallParkDailyWeatherForecast", 'Float'>
  readonly rainFall: Prisma.FieldRef<"BallParkDailyWeatherForecast", 'Float'>
  readonly ballParkId: Prisma.FieldRef<"BallParkDailyWeatherForecast", 'Int'>
  readonly createdAt: Prisma.FieldRef<"BallParkDailyWeatherForecast", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BallParkDailyWeatherForecast", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BallParkDailyWeatherForecast findUnique
 */
export type BallParkDailyWeatherForecastFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkDailyWeatherForecast
   */
  select?: Prisma.BallParkDailyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkDailyWeatherForecast
   */
  omit?: Prisma.BallParkDailyWeatherForecastOmit<ExtArgs> | null
  /**
   * Filter, which BallParkDailyWeatherForecast to fetch.
   */
  where: Prisma.BallParkDailyWeatherForecastWhereUniqueInput
}

/**
 * BallParkDailyWeatherForecast findUniqueOrThrow
 */
export type BallParkDailyWeatherForecastFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkDailyWeatherForecast
   */
  select?: Prisma.BallParkDailyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkDailyWeatherForecast
   */
  omit?: Prisma.BallParkDailyWeatherForecastOmit<ExtArgs> | null
  /**
   * Filter, which BallParkDailyWeatherForecast to fetch.
   */
  where: Prisma.BallParkDailyWeatherForecastWhereUniqueInput
}

/**
 * BallParkDailyWeatherForecast findFirst
 */
export type BallParkDailyWeatherForecastFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkDailyWeatherForecast
   */
  select?: Prisma.BallParkDailyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkDailyWeatherForecast
   */
  omit?: Prisma.BallParkDailyWeatherForecastOmit<ExtArgs> | null
  /**
   * Filter, which BallParkDailyWeatherForecast to fetch.
   */
  where?: Prisma.BallParkDailyWeatherForecastWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BallParkDailyWeatherForecasts to fetch.
   */
  orderBy?: Prisma.BallParkDailyWeatherForecastOrderByWithRelationInput | Prisma.BallParkDailyWeatherForecastOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BallParkDailyWeatherForecasts.
   */
  cursor?: Prisma.BallParkDailyWeatherForecastWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BallParkDailyWeatherForecasts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BallParkDailyWeatherForecasts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BallParkDailyWeatherForecasts.
   */
  distinct?: Prisma.BallParkDailyWeatherForecastScalarFieldEnum | Prisma.BallParkDailyWeatherForecastScalarFieldEnum[]
}

/**
 * BallParkDailyWeatherForecast findFirstOrThrow
 */
export type BallParkDailyWeatherForecastFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkDailyWeatherForecast
   */
  select?: Prisma.BallParkDailyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkDailyWeatherForecast
   */
  omit?: Prisma.BallParkDailyWeatherForecastOmit<ExtArgs> | null
  /**
   * Filter, which BallParkDailyWeatherForecast to fetch.
   */
  where?: Prisma.BallParkDailyWeatherForecastWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BallParkDailyWeatherForecasts to fetch.
   */
  orderBy?: Prisma.BallParkDailyWeatherForecastOrderByWithRelationInput | Prisma.BallParkDailyWeatherForecastOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BallParkDailyWeatherForecasts.
   */
  cursor?: Prisma.BallParkDailyWeatherForecastWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BallParkDailyWeatherForecasts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BallParkDailyWeatherForecasts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BallParkDailyWeatherForecasts.
   */
  distinct?: Prisma.BallParkDailyWeatherForecastScalarFieldEnum | Prisma.BallParkDailyWeatherForecastScalarFieldEnum[]
}

/**
 * BallParkDailyWeatherForecast findMany
 */
export type BallParkDailyWeatherForecastFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkDailyWeatherForecast
   */
  select?: Prisma.BallParkDailyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkDailyWeatherForecast
   */
  omit?: Prisma.BallParkDailyWeatherForecastOmit<ExtArgs> | null
  /**
   * Filter, which BallParkDailyWeatherForecasts to fetch.
   */
  where?: Prisma.BallParkDailyWeatherForecastWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BallParkDailyWeatherForecasts to fetch.
   */
  orderBy?: Prisma.BallParkDailyWeatherForecastOrderByWithRelationInput | Prisma.BallParkDailyWeatherForecastOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BallParkDailyWeatherForecasts.
   */
  cursor?: Prisma.BallParkDailyWeatherForecastWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BallParkDailyWeatherForecasts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BallParkDailyWeatherForecasts.
   */
  skip?: number
  distinct?: Prisma.BallParkDailyWeatherForecastScalarFieldEnum | Prisma.BallParkDailyWeatherForecastScalarFieldEnum[]
}

/**
 * BallParkDailyWeatherForecast create
 */
export type BallParkDailyWeatherForecastCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkDailyWeatherForecast
   */
  select?: Prisma.BallParkDailyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkDailyWeatherForecast
   */
  omit?: Prisma.BallParkDailyWeatherForecastOmit<ExtArgs> | null
  /**
   * The data needed to create a BallParkDailyWeatherForecast.
   */
  data: Prisma.XOR<Prisma.BallParkDailyWeatherForecastCreateInput, Prisma.BallParkDailyWeatherForecastUncheckedCreateInput>
}

/**
 * BallParkDailyWeatherForecast createMany
 */
export type BallParkDailyWeatherForecastCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BallParkDailyWeatherForecasts.
   */
  data: Prisma.BallParkDailyWeatherForecastCreateManyInput | Prisma.BallParkDailyWeatherForecastCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BallParkDailyWeatherForecast update
 */
export type BallParkDailyWeatherForecastUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkDailyWeatherForecast
   */
  select?: Prisma.BallParkDailyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkDailyWeatherForecast
   */
  omit?: Prisma.BallParkDailyWeatherForecastOmit<ExtArgs> | null
  /**
   * The data needed to update a BallParkDailyWeatherForecast.
   */
  data: Prisma.XOR<Prisma.BallParkDailyWeatherForecastUpdateInput, Prisma.BallParkDailyWeatherForecastUncheckedUpdateInput>
  /**
   * Choose, which BallParkDailyWeatherForecast to update.
   */
  where: Prisma.BallParkDailyWeatherForecastWhereUniqueInput
}

/**
 * BallParkDailyWeatherForecast updateMany
 */
export type BallParkDailyWeatherForecastUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BallParkDailyWeatherForecasts.
   */
  data: Prisma.XOR<Prisma.BallParkDailyWeatherForecastUpdateManyMutationInput, Prisma.BallParkDailyWeatherForecastUncheckedUpdateManyInput>
  /**
   * Filter which BallParkDailyWeatherForecasts to update
   */
  where?: Prisma.BallParkDailyWeatherForecastWhereInput
  /**
   * Limit how many BallParkDailyWeatherForecasts to update.
   */
  limit?: number
}

/**
 * BallParkDailyWeatherForecast upsert
 */
export type BallParkDailyWeatherForecastUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkDailyWeatherForecast
   */
  select?: Prisma.BallParkDailyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkDailyWeatherForecast
   */
  omit?: Prisma.BallParkDailyWeatherForecastOmit<ExtArgs> | null
  /**
   * The filter to search for the BallParkDailyWeatherForecast to update in case it exists.
   */
  where: Prisma.BallParkDailyWeatherForecastWhereUniqueInput
  /**
   * In case the BallParkDailyWeatherForecast found by the `where` argument doesn't exist, create a new BallParkDailyWeatherForecast with this data.
   */
  create: Prisma.XOR<Prisma.BallParkDailyWeatherForecastCreateInput, Prisma.BallParkDailyWeatherForecastUncheckedCreateInput>
  /**
   * In case the BallParkDailyWeatherForecast was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BallParkDailyWeatherForecastUpdateInput, Prisma.BallParkDailyWeatherForecastUncheckedUpdateInput>
}

/**
 * BallParkDailyWeatherForecast delete
 */
export type BallParkDailyWeatherForecastDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkDailyWeatherForecast
   */
  select?: Prisma.BallParkDailyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkDailyWeatherForecast
   */
  omit?: Prisma.BallParkDailyWeatherForecastOmit<ExtArgs> | null
  /**
   * Filter which BallParkDailyWeatherForecast to delete.
   */
  where: Prisma.BallParkDailyWeatherForecastWhereUniqueInput
}

/**
 * BallParkDailyWeatherForecast deleteMany
 */
export type BallParkDailyWeatherForecastDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BallParkDailyWeatherForecasts to delete
   */
  where?: Prisma.BallParkDailyWeatherForecastWhereInput
  /**
   * Limit how many BallParkDailyWeatherForecasts to delete.
   */
  limit?: number
}

/**
 * BallParkDailyWeatherForecast without action
 */
export type BallParkDailyWeatherForecastDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkDailyWeatherForecast
   */
  select?: Prisma.BallParkDailyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkDailyWeatherForecast
   */
  omit?: Prisma.BallParkDailyWeatherForecastOmit<ExtArgs> | null
}
