
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BallParkObservedHourlyWeather` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model BallParkObservedHourlyWeather
 * 
 */
export type BallParkObservedHourlyWeatherModel = runtime.Types.Result.DefaultSelection<Prisma.$BallParkObservedHourlyWeatherPayload>

export type AggregateBallParkObservedHourlyWeather = {
  _count: BallParkObservedHourlyWeatherCountAggregateOutputType | null
  _avg: BallParkObservedHourlyWeatherAvgAggregateOutputType | null
  _sum: BallParkObservedHourlyWeatherSumAggregateOutputType | null
  _min: BallParkObservedHourlyWeatherMinAggregateOutputType | null
  _max: BallParkObservedHourlyWeatherMaxAggregateOutputType | null
}

export type BallParkObservedHourlyWeatherAvgAggregateOutputType = {
  id: number | null
  temperature: number | null
  rainFall: number | null
  ballParkId: number | null
}

export type BallParkObservedHourlyWeatherSumAggregateOutputType = {
  id: number | null
  temperature: number | null
  rainFall: number | null
  ballParkId: number | null
}

export type BallParkObservedHourlyWeatherMinAggregateOutputType = {
  id: number | null
  date: Date | null
  temperature: number | null
  rainfallOccurred: boolean | null
  rainFall: number | null
  ballParkId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BallParkObservedHourlyWeatherMaxAggregateOutputType = {
  id: number | null
  date: Date | null
  temperature: number | null
  rainfallOccurred: boolean | null
  rainFall: number | null
  ballParkId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BallParkObservedHourlyWeatherCountAggregateOutputType = {
  id: number
  date: number
  temperature: number
  rainfallOccurred: number
  rainFall: number
  ballParkId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type BallParkObservedHourlyWeatherAvgAggregateInputType = {
  id?: true
  temperature?: true
  rainFall?: true
  ballParkId?: true
}

export type BallParkObservedHourlyWeatherSumAggregateInputType = {
  id?: true
  temperature?: true
  rainFall?: true
  ballParkId?: true
}

export type BallParkObservedHourlyWeatherMinAggregateInputType = {
  id?: true
  date?: true
  temperature?: true
  rainfallOccurred?: true
  rainFall?: true
  ballParkId?: true
  createdAt?: true
  updatedAt?: true
}

export type BallParkObservedHourlyWeatherMaxAggregateInputType = {
  id?: true
  date?: true
  temperature?: true
  rainfallOccurred?: true
  rainFall?: true
  ballParkId?: true
  createdAt?: true
  updatedAt?: true
}

export type BallParkObservedHourlyWeatherCountAggregateInputType = {
  id?: true
  date?: true
  temperature?: true
  rainfallOccurred?: true
  rainFall?: true
  ballParkId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type BallParkObservedHourlyWeatherAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BallParkObservedHourlyWeather to aggregate.
   */
  where?: Prisma.BallParkObservedHourlyWeatherWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BallParkObservedHourlyWeathers to fetch.
   */
  orderBy?: Prisma.BallParkObservedHourlyWeatherOrderByWithRelationInput | Prisma.BallParkObservedHourlyWeatherOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BallParkObservedHourlyWeatherWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BallParkObservedHourlyWeathers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BallParkObservedHourlyWeathers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BallParkObservedHourlyWeathers
  **/
  _count?: true | BallParkObservedHourlyWeatherCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BallParkObservedHourlyWeatherAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BallParkObservedHourlyWeatherSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BallParkObservedHourlyWeatherMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BallParkObservedHourlyWeatherMaxAggregateInputType
}

export type GetBallParkObservedHourlyWeatherAggregateType<T extends BallParkObservedHourlyWeatherAggregateArgs> = {
      [P in keyof T & keyof AggregateBallParkObservedHourlyWeather]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBallParkObservedHourlyWeather[P]>
    : Prisma.GetScalarType<T[P], AggregateBallParkObservedHourlyWeather[P]>
}




export type BallParkObservedHourlyWeatherGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BallParkObservedHourlyWeatherWhereInput
  orderBy?: Prisma.BallParkObservedHourlyWeatherOrderByWithAggregationInput | Prisma.BallParkObservedHourlyWeatherOrderByWithAggregationInput[]
  by: Prisma.BallParkObservedHourlyWeatherScalarFieldEnum[] | Prisma.BallParkObservedHourlyWeatherScalarFieldEnum
  having?: Prisma.BallParkObservedHourlyWeatherScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BallParkObservedHourlyWeatherCountAggregateInputType | true
  _avg?: BallParkObservedHourlyWeatherAvgAggregateInputType
  _sum?: BallParkObservedHourlyWeatherSumAggregateInputType
  _min?: BallParkObservedHourlyWeatherMinAggregateInputType
  _max?: BallParkObservedHourlyWeatherMaxAggregateInputType
}

export type BallParkObservedHourlyWeatherGroupByOutputType = {
  id: number
  date: Date
  temperature: number
  rainfallOccurred: boolean
  rainFall: number
  ballParkId: number
  createdAt: Date
  updatedAt: Date
  _count: BallParkObservedHourlyWeatherCountAggregateOutputType | null
  _avg: BallParkObservedHourlyWeatherAvgAggregateOutputType | null
  _sum: BallParkObservedHourlyWeatherSumAggregateOutputType | null
  _min: BallParkObservedHourlyWeatherMinAggregateOutputType | null
  _max: BallParkObservedHourlyWeatherMaxAggregateOutputType | null
}

type GetBallParkObservedHourlyWeatherGroupByPayload<T extends BallParkObservedHourlyWeatherGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BallParkObservedHourlyWeatherGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BallParkObservedHourlyWeatherGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BallParkObservedHourlyWeatherGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BallParkObservedHourlyWeatherGroupByOutputType[P]>
      }
    >
  >



export type BallParkObservedHourlyWeatherWhereInput = {
  AND?: Prisma.BallParkObservedHourlyWeatherWhereInput | Prisma.BallParkObservedHourlyWeatherWhereInput[]
  OR?: Prisma.BallParkObservedHourlyWeatherWhereInput[]
  NOT?: Prisma.BallParkObservedHourlyWeatherWhereInput | Prisma.BallParkObservedHourlyWeatherWhereInput[]
  id?: Prisma.IntFilter<"BallParkObservedHourlyWeather"> | number
  date?: Prisma.DateTimeFilter<"BallParkObservedHourlyWeather"> | Date | string
  temperature?: Prisma.FloatFilter<"BallParkObservedHourlyWeather"> | number
  rainfallOccurred?: Prisma.BoolFilter<"BallParkObservedHourlyWeather"> | boolean
  rainFall?: Prisma.FloatFilter<"BallParkObservedHourlyWeather"> | number
  ballParkId?: Prisma.IntFilter<"BallParkObservedHourlyWeather"> | number
  createdAt?: Prisma.DateTimeFilter<"BallParkObservedHourlyWeather"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BallParkObservedHourlyWeather"> | Date | string
}

export type BallParkObservedHourlyWeatherOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  rainfallOccurred?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BallParkObservedHourlyWeatherWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  ballParkId_date?: Prisma.BallParkObservedHourlyWeatherBallParkIdDateCompoundUniqueInput
  AND?: Prisma.BallParkObservedHourlyWeatherWhereInput | Prisma.BallParkObservedHourlyWeatherWhereInput[]
  OR?: Prisma.BallParkObservedHourlyWeatherWhereInput[]
  NOT?: Prisma.BallParkObservedHourlyWeatherWhereInput | Prisma.BallParkObservedHourlyWeatherWhereInput[]
  date?: Prisma.DateTimeFilter<"BallParkObservedHourlyWeather"> | Date | string
  temperature?: Prisma.FloatFilter<"BallParkObservedHourlyWeather"> | number
  rainfallOccurred?: Prisma.BoolFilter<"BallParkObservedHourlyWeather"> | boolean
  rainFall?: Prisma.FloatFilter<"BallParkObservedHourlyWeather"> | number
  ballParkId?: Prisma.IntFilter<"BallParkObservedHourlyWeather"> | number
  createdAt?: Prisma.DateTimeFilter<"BallParkObservedHourlyWeather"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BallParkObservedHourlyWeather"> | Date | string
}, "id" | "ballParkId_date">

export type BallParkObservedHourlyWeatherOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  rainfallOccurred?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.BallParkObservedHourlyWeatherCountOrderByAggregateInput
  _avg?: Prisma.BallParkObservedHourlyWeatherAvgOrderByAggregateInput
  _max?: Prisma.BallParkObservedHourlyWeatherMaxOrderByAggregateInput
  _min?: Prisma.BallParkObservedHourlyWeatherMinOrderByAggregateInput
  _sum?: Prisma.BallParkObservedHourlyWeatherSumOrderByAggregateInput
}

export type BallParkObservedHourlyWeatherScalarWhereWithAggregatesInput = {
  AND?: Prisma.BallParkObservedHourlyWeatherScalarWhereWithAggregatesInput | Prisma.BallParkObservedHourlyWeatherScalarWhereWithAggregatesInput[]
  OR?: Prisma.BallParkObservedHourlyWeatherScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BallParkObservedHourlyWeatherScalarWhereWithAggregatesInput | Prisma.BallParkObservedHourlyWeatherScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"BallParkObservedHourlyWeather"> | number
  date?: Prisma.DateTimeWithAggregatesFilter<"BallParkObservedHourlyWeather"> | Date | string
  temperature?: Prisma.FloatWithAggregatesFilter<"BallParkObservedHourlyWeather"> | number
  rainfallOccurred?: Prisma.BoolWithAggregatesFilter<"BallParkObservedHourlyWeather"> | boolean
  rainFall?: Prisma.FloatWithAggregatesFilter<"BallParkObservedHourlyWeather"> | number
  ballParkId?: Prisma.IntWithAggregatesFilter<"BallParkObservedHourlyWeather"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BallParkObservedHourlyWeather"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BallParkObservedHourlyWeather"> | Date | string
}

export type BallParkObservedHourlyWeatherCreateInput = {
  date: Date | string
  temperature: number
  rainfallOccurred: boolean
  rainFall: number
  ballParkId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BallParkObservedHourlyWeatherUncheckedCreateInput = {
  id?: number
  date: Date | string
  temperature: number
  rainfallOccurred: boolean
  rainFall: number
  ballParkId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BallParkObservedHourlyWeatherUpdateInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  temperature?: Prisma.FloatFieldUpdateOperationsInput | number
  rainfallOccurred?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rainFall?: Prisma.FloatFieldUpdateOperationsInput | number
  ballParkId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BallParkObservedHourlyWeatherUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  temperature?: Prisma.FloatFieldUpdateOperationsInput | number
  rainfallOccurred?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rainFall?: Prisma.FloatFieldUpdateOperationsInput | number
  ballParkId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BallParkObservedHourlyWeatherCreateManyInput = {
  id?: number
  date: Date | string
  temperature: number
  rainfallOccurred: boolean
  rainFall: number
  ballParkId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BallParkObservedHourlyWeatherUpdateManyMutationInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  temperature?: Prisma.FloatFieldUpdateOperationsInput | number
  rainfallOccurred?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rainFall?: Prisma.FloatFieldUpdateOperationsInput | number
  ballParkId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BallParkObservedHourlyWeatherUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  temperature?: Prisma.FloatFieldUpdateOperationsInput | number
  rainfallOccurred?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rainFall?: Prisma.FloatFieldUpdateOperationsInput | number
  ballParkId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BallParkObservedHourlyWeatherBallParkIdDateCompoundUniqueInput = {
  ballParkId: number
  date: Date | string
}

export type BallParkObservedHourlyWeatherCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  rainfallOccurred?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BallParkObservedHourlyWeatherAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
}

export type BallParkObservedHourlyWeatherMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  rainfallOccurred?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BallParkObservedHourlyWeatherMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  rainfallOccurred?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BallParkObservedHourlyWeatherSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
}



export type BallParkObservedHourlyWeatherSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  temperature?: boolean
  rainfallOccurred?: boolean
  rainFall?: boolean
  ballParkId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["ballParkObservedHourlyWeather"]>



export type BallParkObservedHourlyWeatherSelectScalar = {
  id?: boolean
  date?: boolean
  temperature?: boolean
  rainfallOccurred?: boolean
  rainFall?: boolean
  ballParkId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type BallParkObservedHourlyWeatherOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "temperature" | "rainfallOccurred" | "rainFall" | "ballParkId" | "createdAt" | "updatedAt", ExtArgs["result"]["ballParkObservedHourlyWeather"]>

export type $BallParkObservedHourlyWeatherPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BallParkObservedHourlyWeather"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    date: Date
    temperature: number
    rainfallOccurred: boolean
    rainFall: number
    ballParkId: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["ballParkObservedHourlyWeather"]>
  composites: {}
}

export type BallParkObservedHourlyWeatherGetPayload<S extends boolean | null | undefined | BallParkObservedHourlyWeatherDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BallParkObservedHourlyWeatherPayload, S>

export type BallParkObservedHourlyWeatherCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BallParkObservedHourlyWeatherFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BallParkObservedHourlyWeatherCountAggregateInputType | true
  }

export interface BallParkObservedHourlyWeatherDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BallParkObservedHourlyWeather'], meta: { name: 'BallParkObservedHourlyWeather' } }
  /**
   * Find zero or one BallParkObservedHourlyWeather that matches the filter.
   * @param {BallParkObservedHourlyWeatherFindUniqueArgs} args - Arguments to find a BallParkObservedHourlyWeather
   * @example
   * // Get one BallParkObservedHourlyWeather
   * const ballParkObservedHourlyWeather = await prisma.ballParkObservedHourlyWeather.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BallParkObservedHourlyWeatherFindUniqueArgs>(args: Prisma.SelectSubset<T, BallParkObservedHourlyWeatherFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BallParkObservedHourlyWeatherClient<runtime.Types.Result.GetResult<Prisma.$BallParkObservedHourlyWeatherPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BallParkObservedHourlyWeather that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BallParkObservedHourlyWeatherFindUniqueOrThrowArgs} args - Arguments to find a BallParkObservedHourlyWeather
   * @example
   * // Get one BallParkObservedHourlyWeather
   * const ballParkObservedHourlyWeather = await prisma.ballParkObservedHourlyWeather.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BallParkObservedHourlyWeatherFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BallParkObservedHourlyWeatherFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BallParkObservedHourlyWeatherClient<runtime.Types.Result.GetResult<Prisma.$BallParkObservedHourlyWeatherPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BallParkObservedHourlyWeather that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkObservedHourlyWeatherFindFirstArgs} args - Arguments to find a BallParkObservedHourlyWeather
   * @example
   * // Get one BallParkObservedHourlyWeather
   * const ballParkObservedHourlyWeather = await prisma.ballParkObservedHourlyWeather.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BallParkObservedHourlyWeatherFindFirstArgs>(args?: Prisma.SelectSubset<T, BallParkObservedHourlyWeatherFindFirstArgs<ExtArgs>>): Prisma.Prisma__BallParkObservedHourlyWeatherClient<runtime.Types.Result.GetResult<Prisma.$BallParkObservedHourlyWeatherPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BallParkObservedHourlyWeather that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkObservedHourlyWeatherFindFirstOrThrowArgs} args - Arguments to find a BallParkObservedHourlyWeather
   * @example
   * // Get one BallParkObservedHourlyWeather
   * const ballParkObservedHourlyWeather = await prisma.ballParkObservedHourlyWeather.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BallParkObservedHourlyWeatherFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BallParkObservedHourlyWeatherFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BallParkObservedHourlyWeatherClient<runtime.Types.Result.GetResult<Prisma.$BallParkObservedHourlyWeatherPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BallParkObservedHourlyWeathers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkObservedHourlyWeatherFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BallParkObservedHourlyWeathers
   * const ballParkObservedHourlyWeathers = await prisma.ballParkObservedHourlyWeather.findMany()
   * 
   * // Get first 10 BallParkObservedHourlyWeathers
   * const ballParkObservedHourlyWeathers = await prisma.ballParkObservedHourlyWeather.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ballParkObservedHourlyWeatherWithIdOnly = await prisma.ballParkObservedHourlyWeather.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BallParkObservedHourlyWeatherFindManyArgs>(args?: Prisma.SelectSubset<T, BallParkObservedHourlyWeatherFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BallParkObservedHourlyWeatherPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BallParkObservedHourlyWeather.
   * @param {BallParkObservedHourlyWeatherCreateArgs} args - Arguments to create a BallParkObservedHourlyWeather.
   * @example
   * // Create one BallParkObservedHourlyWeather
   * const BallParkObservedHourlyWeather = await prisma.ballParkObservedHourlyWeather.create({
   *   data: {
   *     // ... data to create a BallParkObservedHourlyWeather
   *   }
   * })
   * 
   */
  create<T extends BallParkObservedHourlyWeatherCreateArgs>(args: Prisma.SelectSubset<T, BallParkObservedHourlyWeatherCreateArgs<ExtArgs>>): Prisma.Prisma__BallParkObservedHourlyWeatherClient<runtime.Types.Result.GetResult<Prisma.$BallParkObservedHourlyWeatherPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BallParkObservedHourlyWeathers.
   * @param {BallParkObservedHourlyWeatherCreateManyArgs} args - Arguments to create many BallParkObservedHourlyWeathers.
   * @example
   * // Create many BallParkObservedHourlyWeathers
   * const ballParkObservedHourlyWeather = await prisma.ballParkObservedHourlyWeather.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BallParkObservedHourlyWeatherCreateManyArgs>(args?: Prisma.SelectSubset<T, BallParkObservedHourlyWeatherCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a BallParkObservedHourlyWeather.
   * @param {BallParkObservedHourlyWeatherDeleteArgs} args - Arguments to delete one BallParkObservedHourlyWeather.
   * @example
   * // Delete one BallParkObservedHourlyWeather
   * const BallParkObservedHourlyWeather = await prisma.ballParkObservedHourlyWeather.delete({
   *   where: {
   *     // ... filter to delete one BallParkObservedHourlyWeather
   *   }
   * })
   * 
   */
  delete<T extends BallParkObservedHourlyWeatherDeleteArgs>(args: Prisma.SelectSubset<T, BallParkObservedHourlyWeatherDeleteArgs<ExtArgs>>): Prisma.Prisma__BallParkObservedHourlyWeatherClient<runtime.Types.Result.GetResult<Prisma.$BallParkObservedHourlyWeatherPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BallParkObservedHourlyWeather.
   * @param {BallParkObservedHourlyWeatherUpdateArgs} args - Arguments to update one BallParkObservedHourlyWeather.
   * @example
   * // Update one BallParkObservedHourlyWeather
   * const ballParkObservedHourlyWeather = await prisma.ballParkObservedHourlyWeather.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BallParkObservedHourlyWeatherUpdateArgs>(args: Prisma.SelectSubset<T, BallParkObservedHourlyWeatherUpdateArgs<ExtArgs>>): Prisma.Prisma__BallParkObservedHourlyWeatherClient<runtime.Types.Result.GetResult<Prisma.$BallParkObservedHourlyWeatherPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BallParkObservedHourlyWeathers.
   * @param {BallParkObservedHourlyWeatherDeleteManyArgs} args - Arguments to filter BallParkObservedHourlyWeathers to delete.
   * @example
   * // Delete a few BallParkObservedHourlyWeathers
   * const { count } = await prisma.ballParkObservedHourlyWeather.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BallParkObservedHourlyWeatherDeleteManyArgs>(args?: Prisma.SelectSubset<T, BallParkObservedHourlyWeatherDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BallParkObservedHourlyWeathers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkObservedHourlyWeatherUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BallParkObservedHourlyWeathers
   * const ballParkObservedHourlyWeather = await prisma.ballParkObservedHourlyWeather.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BallParkObservedHourlyWeatherUpdateManyArgs>(args: Prisma.SelectSubset<T, BallParkObservedHourlyWeatherUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one BallParkObservedHourlyWeather.
   * @param {BallParkObservedHourlyWeatherUpsertArgs} args - Arguments to update or create a BallParkObservedHourlyWeather.
   * @example
   * // Update or create a BallParkObservedHourlyWeather
   * const ballParkObservedHourlyWeather = await prisma.ballParkObservedHourlyWeather.upsert({
   *   create: {
   *     // ... data to create a BallParkObservedHourlyWeather
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BallParkObservedHourlyWeather we want to update
   *   }
   * })
   */
  upsert<T extends BallParkObservedHourlyWeatherUpsertArgs>(args: Prisma.SelectSubset<T, BallParkObservedHourlyWeatherUpsertArgs<ExtArgs>>): Prisma.Prisma__BallParkObservedHourlyWeatherClient<runtime.Types.Result.GetResult<Prisma.$BallParkObservedHourlyWeatherPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BallParkObservedHourlyWeathers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkObservedHourlyWeatherCountArgs} args - Arguments to filter BallParkObservedHourlyWeathers to count.
   * @example
   * // Count the number of BallParkObservedHourlyWeathers
   * const count = await prisma.ballParkObservedHourlyWeather.count({
   *   where: {
   *     // ... the filter for the BallParkObservedHourlyWeathers we want to count
   *   }
   * })
  **/
  count<T extends BallParkObservedHourlyWeatherCountArgs>(
    args?: Prisma.Subset<T, BallParkObservedHourlyWeatherCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BallParkObservedHourlyWeatherCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BallParkObservedHourlyWeather.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkObservedHourlyWeatherAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BallParkObservedHourlyWeatherAggregateArgs>(args: Prisma.Subset<T, BallParkObservedHourlyWeatherAggregateArgs>): Prisma.PrismaPromise<GetBallParkObservedHourlyWeatherAggregateType<T>>

  /**
   * Group by BallParkObservedHourlyWeather.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkObservedHourlyWeatherGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BallParkObservedHourlyWeatherGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BallParkObservedHourlyWeatherGroupByArgs['orderBy'] }
      : { orderBy?: BallParkObservedHourlyWeatherGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BallParkObservedHourlyWeatherGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBallParkObservedHourlyWeatherGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BallParkObservedHourlyWeather model
 */
readonly fields: BallParkObservedHourlyWeatherFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BallParkObservedHourlyWeather.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BallParkObservedHourlyWeatherClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BallParkObservedHourlyWeather model
 */
export interface BallParkObservedHourlyWeatherFieldRefs {
  readonly id: Prisma.FieldRef<"BallParkObservedHourlyWeather", 'Int'>
  readonly date: Prisma.FieldRef<"BallParkObservedHourlyWeather", 'DateTime'>
  readonly temperature: Prisma.FieldRef<"BallParkObservedHourlyWeather", 'Float'>
  readonly rainfallOccurred: Prisma.FieldRef<"BallParkObservedHourlyWeather", 'Boolean'>
  readonly rainFall: Prisma.FieldRef<"BallParkObservedHourlyWeather", 'Float'>
  readonly ballParkId: Prisma.FieldRef<"BallParkObservedHourlyWeather", 'Int'>
  readonly createdAt: Prisma.FieldRef<"BallParkObservedHourlyWeather", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BallParkObservedHourlyWeather", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BallParkObservedHourlyWeather findUnique
 */
export type BallParkObservedHourlyWeatherFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkObservedHourlyWeather
   */
  select?: Prisma.BallParkObservedHourlyWeatherSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkObservedHourlyWeather
   */
  omit?: Prisma.BallParkObservedHourlyWeatherOmit<ExtArgs> | null
  /**
   * Filter, which BallParkObservedHourlyWeather to fetch.
   */
  where: Prisma.BallParkObservedHourlyWeatherWhereUniqueInput
}

/**
 * BallParkObservedHourlyWeather findUniqueOrThrow
 */
export type BallParkObservedHourlyWeatherFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkObservedHourlyWeather
   */
  select?: Prisma.BallParkObservedHourlyWeatherSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkObservedHourlyWeather
   */
  omit?: Prisma.BallParkObservedHourlyWeatherOmit<ExtArgs> | null
  /**
   * Filter, which BallParkObservedHourlyWeather to fetch.
   */
  where: Prisma.BallParkObservedHourlyWeatherWhereUniqueInput
}

/**
 * BallParkObservedHourlyWeather findFirst
 */
export type BallParkObservedHourlyWeatherFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkObservedHourlyWeather
   */
  select?: Prisma.BallParkObservedHourlyWeatherSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkObservedHourlyWeather
   */
  omit?: Prisma.BallParkObservedHourlyWeatherOmit<ExtArgs> | null
  /**
   * Filter, which BallParkObservedHourlyWeather to fetch.
   */
  where?: Prisma.BallParkObservedHourlyWeatherWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BallParkObservedHourlyWeathers to fetch.
   */
  orderBy?: Prisma.BallParkObservedHourlyWeatherOrderByWithRelationInput | Prisma.BallParkObservedHourlyWeatherOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BallParkObservedHourlyWeathers.
   */
  cursor?: Prisma.BallParkObservedHourlyWeatherWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BallParkObservedHourlyWeathers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BallParkObservedHourlyWeathers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BallParkObservedHourlyWeathers.
   */
  distinct?: Prisma.BallParkObservedHourlyWeatherScalarFieldEnum | Prisma.BallParkObservedHourlyWeatherScalarFieldEnum[]
}

/**
 * BallParkObservedHourlyWeather findFirstOrThrow
 */
export type BallParkObservedHourlyWeatherFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkObservedHourlyWeather
   */
  select?: Prisma.BallParkObservedHourlyWeatherSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkObservedHourlyWeather
   */
  omit?: Prisma.BallParkObservedHourlyWeatherOmit<ExtArgs> | null
  /**
   * Filter, which BallParkObservedHourlyWeather to fetch.
   */
  where?: Prisma.BallParkObservedHourlyWeatherWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BallParkObservedHourlyWeathers to fetch.
   */
  orderBy?: Prisma.BallParkObservedHourlyWeatherOrderByWithRelationInput | Prisma.BallParkObservedHourlyWeatherOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BallParkObservedHourlyWeathers.
   */
  cursor?: Prisma.BallParkObservedHourlyWeatherWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BallParkObservedHourlyWeathers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BallParkObservedHourlyWeathers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BallParkObservedHourlyWeathers.
   */
  distinct?: Prisma.BallParkObservedHourlyWeatherScalarFieldEnum | Prisma.BallParkObservedHourlyWeatherScalarFieldEnum[]
}

/**
 * BallParkObservedHourlyWeather findMany
 */
export type BallParkObservedHourlyWeatherFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkObservedHourlyWeather
   */
  select?: Prisma.BallParkObservedHourlyWeatherSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkObservedHourlyWeather
   */
  omit?: Prisma.BallParkObservedHourlyWeatherOmit<ExtArgs> | null
  /**
   * Filter, which BallParkObservedHourlyWeathers to fetch.
   */
  where?: Prisma.BallParkObservedHourlyWeatherWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BallParkObservedHourlyWeathers to fetch.
   */
  orderBy?: Prisma.BallParkObservedHourlyWeatherOrderByWithRelationInput | Prisma.BallParkObservedHourlyWeatherOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BallParkObservedHourlyWeathers.
   */
  cursor?: Prisma.BallParkObservedHourlyWeatherWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BallParkObservedHourlyWeathers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BallParkObservedHourlyWeathers.
   */
  skip?: number
  distinct?: Prisma.BallParkObservedHourlyWeatherScalarFieldEnum | Prisma.BallParkObservedHourlyWeatherScalarFieldEnum[]
}

/**
 * BallParkObservedHourlyWeather create
 */
export type BallParkObservedHourlyWeatherCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkObservedHourlyWeather
   */
  select?: Prisma.BallParkObservedHourlyWeatherSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkObservedHourlyWeather
   */
  omit?: Prisma.BallParkObservedHourlyWeatherOmit<ExtArgs> | null
  /**
   * The data needed to create a BallParkObservedHourlyWeather.
   */
  data: Prisma.XOR<Prisma.BallParkObservedHourlyWeatherCreateInput, Prisma.BallParkObservedHourlyWeatherUncheckedCreateInput>
}

/**
 * BallParkObservedHourlyWeather createMany
 */
export type BallParkObservedHourlyWeatherCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BallParkObservedHourlyWeathers.
   */
  data: Prisma.BallParkObservedHourlyWeatherCreateManyInput | Prisma.BallParkObservedHourlyWeatherCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BallParkObservedHourlyWeather update
 */
export type BallParkObservedHourlyWeatherUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkObservedHourlyWeather
   */
  select?: Prisma.BallParkObservedHourlyWeatherSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkObservedHourlyWeather
   */
  omit?: Prisma.BallParkObservedHourlyWeatherOmit<ExtArgs> | null
  /**
   * The data needed to update a BallParkObservedHourlyWeather.
   */
  data: Prisma.XOR<Prisma.BallParkObservedHourlyWeatherUpdateInput, Prisma.BallParkObservedHourlyWeatherUncheckedUpdateInput>
  /**
   * Choose, which BallParkObservedHourlyWeather to update.
   */
  where: Prisma.BallParkObservedHourlyWeatherWhereUniqueInput
}

/**
 * BallParkObservedHourlyWeather updateMany
 */
export type BallParkObservedHourlyWeatherUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BallParkObservedHourlyWeathers.
   */
  data: Prisma.XOR<Prisma.BallParkObservedHourlyWeatherUpdateManyMutationInput, Prisma.BallParkObservedHourlyWeatherUncheckedUpdateManyInput>
  /**
   * Filter which BallParkObservedHourlyWeathers to update
   */
  where?: Prisma.BallParkObservedHourlyWeatherWhereInput
  /**
   * Limit how many BallParkObservedHourlyWeathers to update.
   */
  limit?: number
}

/**
 * BallParkObservedHourlyWeather upsert
 */
export type BallParkObservedHourlyWeatherUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkObservedHourlyWeather
   */
  select?: Prisma.BallParkObservedHourlyWeatherSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkObservedHourlyWeather
   */
  omit?: Prisma.BallParkObservedHourlyWeatherOmit<ExtArgs> | null
  /**
   * The filter to search for the BallParkObservedHourlyWeather to update in case it exists.
   */
  where: Prisma.BallParkObservedHourlyWeatherWhereUniqueInput
  /**
   * In case the BallParkObservedHourlyWeather found by the `where` argument doesn't exist, create a new BallParkObservedHourlyWeather with this data.
   */
  create: Prisma.XOR<Prisma.BallParkObservedHourlyWeatherCreateInput, Prisma.BallParkObservedHourlyWeatherUncheckedCreateInput>
  /**
   * In case the BallParkObservedHourlyWeather was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BallParkObservedHourlyWeatherUpdateInput, Prisma.BallParkObservedHourlyWeatherUncheckedUpdateInput>
}

/**
 * BallParkObservedHourlyWeather delete
 */
export type BallParkObservedHourlyWeatherDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkObservedHourlyWeather
   */
  select?: Prisma.BallParkObservedHourlyWeatherSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkObservedHourlyWeather
   */
  omit?: Prisma.BallParkObservedHourlyWeatherOmit<ExtArgs> | null
  /**
   * Filter which BallParkObservedHourlyWeather to delete.
   */
  where: Prisma.BallParkObservedHourlyWeatherWhereUniqueInput
}

/**
 * BallParkObservedHourlyWeather deleteMany
 */
export type BallParkObservedHourlyWeatherDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BallParkObservedHourlyWeathers to delete
   */
  where?: Prisma.BallParkObservedHourlyWeatherWhereInput
  /**
   * Limit how many BallParkObservedHourlyWeathers to delete.
   */
  limit?: number
}

/**
 * BallParkObservedHourlyWeather without action
 */
export type BallParkObservedHourlyWeatherDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkObservedHourlyWeather
   */
  select?: Prisma.BallParkObservedHourlyWeatherSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkObservedHourlyWeather
   */
  omit?: Prisma.BallParkObservedHourlyWeatherOmit<ExtArgs> | null
}
