
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BallParkHourlyWeatherForecast` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model BallParkHourlyWeatherForecast
 * 
 */
export type BallParkHourlyWeatherForecastModel = runtime.Types.Result.DefaultSelection<Prisma.$BallParkHourlyWeatherForecastPayload>

export type AggregateBallParkHourlyWeatherForecast = {
  _count: BallParkHourlyWeatherForecastCountAggregateOutputType | null
  _avg: BallParkHourlyWeatherForecastAvgAggregateOutputType | null
  _sum: BallParkHourlyWeatherForecastSumAggregateOutputType | null
  _min: BallParkHourlyWeatherForecastMinAggregateOutputType | null
  _max: BallParkHourlyWeatherForecastMaxAggregateOutputType | null
}

export type BallParkHourlyWeatherForecastAvgAggregateOutputType = {
  id: number | null
  weatherCode: number | null
  temperature: number | null
  precipitationProbability: number | null
  rainFall: number | null
  ballParkId: number | null
}

export type BallParkHourlyWeatherForecastSumAggregateOutputType = {
  id: number | null
  weatherCode: number | null
  temperature: number | null
  precipitationProbability: number | null
  rainFall: number | null
  ballParkId: number | null
}

export type BallParkHourlyWeatherForecastMinAggregateOutputType = {
  id: number | null
  date: Date | null
  weatherCode: number | null
  temperature: number | null
  precipitationProbability: number | null
  rainFall: number | null
  ballParkId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BallParkHourlyWeatherForecastMaxAggregateOutputType = {
  id: number | null
  date: Date | null
  weatherCode: number | null
  temperature: number | null
  precipitationProbability: number | null
  rainFall: number | null
  ballParkId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type BallParkHourlyWeatherForecastCountAggregateOutputType = {
  id: number
  date: number
  weatherCode: number
  temperature: number
  precipitationProbability: number
  rainFall: number
  ballParkId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type BallParkHourlyWeatherForecastAvgAggregateInputType = {
  id?: true
  weatherCode?: true
  temperature?: true
  precipitationProbability?: true
  rainFall?: true
  ballParkId?: true
}

export type BallParkHourlyWeatherForecastSumAggregateInputType = {
  id?: true
  weatherCode?: true
  temperature?: true
  precipitationProbability?: true
  rainFall?: true
  ballParkId?: true
}

export type BallParkHourlyWeatherForecastMinAggregateInputType = {
  id?: true
  date?: true
  weatherCode?: true
  temperature?: true
  precipitationProbability?: true
  rainFall?: true
  ballParkId?: true
  createdAt?: true
  updatedAt?: true
}

export type BallParkHourlyWeatherForecastMaxAggregateInputType = {
  id?: true
  date?: true
  weatherCode?: true
  temperature?: true
  precipitationProbability?: true
  rainFall?: true
  ballParkId?: true
  createdAt?: true
  updatedAt?: true
}

export type BallParkHourlyWeatherForecastCountAggregateInputType = {
  id?: true
  date?: true
  weatherCode?: true
  temperature?: true
  precipitationProbability?: true
  rainFall?: true
  ballParkId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type BallParkHourlyWeatherForecastAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BallParkHourlyWeatherForecast to aggregate.
   */
  where?: Prisma.BallParkHourlyWeatherForecastWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BallParkHourlyWeatherForecasts to fetch.
   */
  orderBy?: Prisma.BallParkHourlyWeatherForecastOrderByWithRelationInput | Prisma.BallParkHourlyWeatherForecastOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BallParkHourlyWeatherForecastWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BallParkHourlyWeatherForecasts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BallParkHourlyWeatherForecasts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BallParkHourlyWeatherForecasts
  **/
  _count?: true | BallParkHourlyWeatherForecastCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BallParkHourlyWeatherForecastAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BallParkHourlyWeatherForecastSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BallParkHourlyWeatherForecastMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BallParkHourlyWeatherForecastMaxAggregateInputType
}

export type GetBallParkHourlyWeatherForecastAggregateType<T extends BallParkHourlyWeatherForecastAggregateArgs> = {
      [P in keyof T & keyof AggregateBallParkHourlyWeatherForecast]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBallParkHourlyWeatherForecast[P]>
    : Prisma.GetScalarType<T[P], AggregateBallParkHourlyWeatherForecast[P]>
}




export type BallParkHourlyWeatherForecastGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BallParkHourlyWeatherForecastWhereInput
  orderBy?: Prisma.BallParkHourlyWeatherForecastOrderByWithAggregationInput | Prisma.BallParkHourlyWeatherForecastOrderByWithAggregationInput[]
  by: Prisma.BallParkHourlyWeatherForecastScalarFieldEnum[] | Prisma.BallParkHourlyWeatherForecastScalarFieldEnum
  having?: Prisma.BallParkHourlyWeatherForecastScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BallParkHourlyWeatherForecastCountAggregateInputType | true
  _avg?: BallParkHourlyWeatherForecastAvgAggregateInputType
  _sum?: BallParkHourlyWeatherForecastSumAggregateInputType
  _min?: BallParkHourlyWeatherForecastMinAggregateInputType
  _max?: BallParkHourlyWeatherForecastMaxAggregateInputType
}

export type BallParkHourlyWeatherForecastGroupByOutputType = {
  id: number
  date: Date
  weatherCode: number
  temperature: number
  precipitationProbability: number
  rainFall: number
  ballParkId: number
  createdAt: Date
  updatedAt: Date
  _count: BallParkHourlyWeatherForecastCountAggregateOutputType | null
  _avg: BallParkHourlyWeatherForecastAvgAggregateOutputType | null
  _sum: BallParkHourlyWeatherForecastSumAggregateOutputType | null
  _min: BallParkHourlyWeatherForecastMinAggregateOutputType | null
  _max: BallParkHourlyWeatherForecastMaxAggregateOutputType | null
}

type GetBallParkHourlyWeatherForecastGroupByPayload<T extends BallParkHourlyWeatherForecastGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BallParkHourlyWeatherForecastGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BallParkHourlyWeatherForecastGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BallParkHourlyWeatherForecastGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BallParkHourlyWeatherForecastGroupByOutputType[P]>
      }
    >
  >



export type BallParkHourlyWeatherForecastWhereInput = {
  AND?: Prisma.BallParkHourlyWeatherForecastWhereInput | Prisma.BallParkHourlyWeatherForecastWhereInput[]
  OR?: Prisma.BallParkHourlyWeatherForecastWhereInput[]
  NOT?: Prisma.BallParkHourlyWeatherForecastWhereInput | Prisma.BallParkHourlyWeatherForecastWhereInput[]
  id?: Prisma.IntFilter<"BallParkHourlyWeatherForecast"> | number
  date?: Prisma.DateTimeFilter<"BallParkHourlyWeatherForecast"> | Date | string
  weatherCode?: Prisma.IntFilter<"BallParkHourlyWeatherForecast"> | number
  temperature?: Prisma.FloatFilter<"BallParkHourlyWeatherForecast"> | number
  precipitationProbability?: Prisma.FloatFilter<"BallParkHourlyWeatherForecast"> | number
  rainFall?: Prisma.FloatFilter<"BallParkHourlyWeatherForecast"> | number
  ballParkId?: Prisma.IntFilter<"BallParkHourlyWeatherForecast"> | number
  createdAt?: Prisma.DateTimeFilter<"BallParkHourlyWeatherForecast"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BallParkHourlyWeatherForecast"> | Date | string
}

export type BallParkHourlyWeatherForecastOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  weatherCode?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  precipitationProbability?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BallParkHourlyWeatherForecastWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  ballParkId_date?: Prisma.BallParkHourlyWeatherForecastBallParkIdDateCompoundUniqueInput
  AND?: Prisma.BallParkHourlyWeatherForecastWhereInput | Prisma.BallParkHourlyWeatherForecastWhereInput[]
  OR?: Prisma.BallParkHourlyWeatherForecastWhereInput[]
  NOT?: Prisma.BallParkHourlyWeatherForecastWhereInput | Prisma.BallParkHourlyWeatherForecastWhereInput[]
  date?: Prisma.DateTimeFilter<"BallParkHourlyWeatherForecast"> | Date | string
  weatherCode?: Prisma.IntFilter<"BallParkHourlyWeatherForecast"> | number
  temperature?: Prisma.FloatFilter<"BallParkHourlyWeatherForecast"> | number
  precipitationProbability?: Prisma.FloatFilter<"BallParkHourlyWeatherForecast"> | number
  rainFall?: Prisma.FloatFilter<"BallParkHourlyWeatherForecast"> | number
  ballParkId?: Prisma.IntFilter<"BallParkHourlyWeatherForecast"> | number
  createdAt?: Prisma.DateTimeFilter<"BallParkHourlyWeatherForecast"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"BallParkHourlyWeatherForecast"> | Date | string
}, "id" | "ballParkId_date">

export type BallParkHourlyWeatherForecastOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  weatherCode?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  precipitationProbability?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.BallParkHourlyWeatherForecastCountOrderByAggregateInput
  _avg?: Prisma.BallParkHourlyWeatherForecastAvgOrderByAggregateInput
  _max?: Prisma.BallParkHourlyWeatherForecastMaxOrderByAggregateInput
  _min?: Prisma.BallParkHourlyWeatherForecastMinOrderByAggregateInput
  _sum?: Prisma.BallParkHourlyWeatherForecastSumOrderByAggregateInput
}

export type BallParkHourlyWeatherForecastScalarWhereWithAggregatesInput = {
  AND?: Prisma.BallParkHourlyWeatherForecastScalarWhereWithAggregatesInput | Prisma.BallParkHourlyWeatherForecastScalarWhereWithAggregatesInput[]
  OR?: Prisma.BallParkHourlyWeatherForecastScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BallParkHourlyWeatherForecastScalarWhereWithAggregatesInput | Prisma.BallParkHourlyWeatherForecastScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"BallParkHourlyWeatherForecast"> | number
  date?: Prisma.DateTimeWithAggregatesFilter<"BallParkHourlyWeatherForecast"> | Date | string
  weatherCode?: Prisma.IntWithAggregatesFilter<"BallParkHourlyWeatherForecast"> | number
  temperature?: Prisma.FloatWithAggregatesFilter<"BallParkHourlyWeatherForecast"> | number
  precipitationProbability?: Prisma.FloatWithAggregatesFilter<"BallParkHourlyWeatherForecast"> | number
  rainFall?: Prisma.FloatWithAggregatesFilter<"BallParkHourlyWeatherForecast"> | number
  ballParkId?: Prisma.IntWithAggregatesFilter<"BallParkHourlyWeatherForecast"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"BallParkHourlyWeatherForecast"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"BallParkHourlyWeatherForecast"> | Date | string
}

export type BallParkHourlyWeatherForecastCreateInput = {
  date: Date | string
  weatherCode: number
  temperature: number
  precipitationProbability: number
  rainFall: number
  ballParkId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BallParkHourlyWeatherForecastUncheckedCreateInput = {
  id?: number
  date: Date | string
  weatherCode: number
  temperature: number
  precipitationProbability: number
  rainFall: number
  ballParkId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BallParkHourlyWeatherForecastUpdateInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weatherCode?: Prisma.IntFieldUpdateOperationsInput | number
  temperature?: Prisma.FloatFieldUpdateOperationsInput | number
  precipitationProbability?: Prisma.FloatFieldUpdateOperationsInput | number
  rainFall?: Prisma.FloatFieldUpdateOperationsInput | number
  ballParkId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BallParkHourlyWeatherForecastUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weatherCode?: Prisma.IntFieldUpdateOperationsInput | number
  temperature?: Prisma.FloatFieldUpdateOperationsInput | number
  precipitationProbability?: Prisma.FloatFieldUpdateOperationsInput | number
  rainFall?: Prisma.FloatFieldUpdateOperationsInput | number
  ballParkId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BallParkHourlyWeatherForecastCreateManyInput = {
  id?: number
  date: Date | string
  weatherCode: number
  temperature: number
  precipitationProbability: number
  rainFall: number
  ballParkId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type BallParkHourlyWeatherForecastUpdateManyMutationInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weatherCode?: Prisma.IntFieldUpdateOperationsInput | number
  temperature?: Prisma.FloatFieldUpdateOperationsInput | number
  precipitationProbability?: Prisma.FloatFieldUpdateOperationsInput | number
  rainFall?: Prisma.FloatFieldUpdateOperationsInput | number
  ballParkId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BallParkHourlyWeatherForecastUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weatherCode?: Prisma.IntFieldUpdateOperationsInput | number
  temperature?: Prisma.FloatFieldUpdateOperationsInput | number
  precipitationProbability?: Prisma.FloatFieldUpdateOperationsInput | number
  rainFall?: Prisma.FloatFieldUpdateOperationsInput | number
  ballParkId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BallParkHourlyWeatherForecastBallParkIdDateCompoundUniqueInput = {
  ballParkId: number
  date: Date | string
}

export type BallParkHourlyWeatherForecastCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  weatherCode?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  precipitationProbability?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BallParkHourlyWeatherForecastAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  weatherCode?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  precipitationProbability?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
}

export type BallParkHourlyWeatherForecastMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  weatherCode?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  precipitationProbability?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BallParkHourlyWeatherForecastMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  weatherCode?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  precipitationProbability?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type BallParkHourlyWeatherForecastSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  weatherCode?: Prisma.SortOrder
  temperature?: Prisma.SortOrder
  precipitationProbability?: Prisma.SortOrder
  rainFall?: Prisma.SortOrder
  ballParkId?: Prisma.SortOrder
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type BallParkHourlyWeatherForecastSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  weatherCode?: boolean
  temperature?: boolean
  precipitationProbability?: boolean
  rainFall?: boolean
  ballParkId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["ballParkHourlyWeatherForecast"]>



export type BallParkHourlyWeatherForecastSelectScalar = {
  id?: boolean
  date?: boolean
  weatherCode?: boolean
  temperature?: boolean
  precipitationProbability?: boolean
  rainFall?: boolean
  ballParkId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type BallParkHourlyWeatherForecastOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "weatherCode" | "temperature" | "precipitationProbability" | "rainFall" | "ballParkId" | "createdAt" | "updatedAt", ExtArgs["result"]["ballParkHourlyWeatherForecast"]>

export type $BallParkHourlyWeatherForecastPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BallParkHourlyWeatherForecast"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    date: Date
    weatherCode: number
    temperature: number
    precipitationProbability: number
    rainFall: number
    ballParkId: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["ballParkHourlyWeatherForecast"]>
  composites: {}
}

export type BallParkHourlyWeatherForecastGetPayload<S extends boolean | null | undefined | BallParkHourlyWeatherForecastDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BallParkHourlyWeatherForecastPayload, S>

export type BallParkHourlyWeatherForecastCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BallParkHourlyWeatherForecastFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BallParkHourlyWeatherForecastCountAggregateInputType | true
  }

export interface BallParkHourlyWeatherForecastDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BallParkHourlyWeatherForecast'], meta: { name: 'BallParkHourlyWeatherForecast' } }
  /**
   * Find zero or one BallParkHourlyWeatherForecast that matches the filter.
   * @param {BallParkHourlyWeatherForecastFindUniqueArgs} args - Arguments to find a BallParkHourlyWeatherForecast
   * @example
   * // Get one BallParkHourlyWeatherForecast
   * const ballParkHourlyWeatherForecast = await prisma.ballParkHourlyWeatherForecast.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BallParkHourlyWeatherForecastFindUniqueArgs>(args: Prisma.SelectSubset<T, BallParkHourlyWeatherForecastFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BallParkHourlyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkHourlyWeatherForecastPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BallParkHourlyWeatherForecast that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BallParkHourlyWeatherForecastFindUniqueOrThrowArgs} args - Arguments to find a BallParkHourlyWeatherForecast
   * @example
   * // Get one BallParkHourlyWeatherForecast
   * const ballParkHourlyWeatherForecast = await prisma.ballParkHourlyWeatherForecast.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BallParkHourlyWeatherForecastFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BallParkHourlyWeatherForecastFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BallParkHourlyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkHourlyWeatherForecastPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BallParkHourlyWeatherForecast that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkHourlyWeatherForecastFindFirstArgs} args - Arguments to find a BallParkHourlyWeatherForecast
   * @example
   * // Get one BallParkHourlyWeatherForecast
   * const ballParkHourlyWeatherForecast = await prisma.ballParkHourlyWeatherForecast.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BallParkHourlyWeatherForecastFindFirstArgs>(args?: Prisma.SelectSubset<T, BallParkHourlyWeatherForecastFindFirstArgs<ExtArgs>>): Prisma.Prisma__BallParkHourlyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkHourlyWeatherForecastPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BallParkHourlyWeatherForecast that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkHourlyWeatherForecastFindFirstOrThrowArgs} args - Arguments to find a BallParkHourlyWeatherForecast
   * @example
   * // Get one BallParkHourlyWeatherForecast
   * const ballParkHourlyWeatherForecast = await prisma.ballParkHourlyWeatherForecast.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BallParkHourlyWeatherForecastFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BallParkHourlyWeatherForecastFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BallParkHourlyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkHourlyWeatherForecastPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BallParkHourlyWeatherForecasts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkHourlyWeatherForecastFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BallParkHourlyWeatherForecasts
   * const ballParkHourlyWeatherForecasts = await prisma.ballParkHourlyWeatherForecast.findMany()
   * 
   * // Get first 10 BallParkHourlyWeatherForecasts
   * const ballParkHourlyWeatherForecasts = await prisma.ballParkHourlyWeatherForecast.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ballParkHourlyWeatherForecastWithIdOnly = await prisma.ballParkHourlyWeatherForecast.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BallParkHourlyWeatherForecastFindManyArgs>(args?: Prisma.SelectSubset<T, BallParkHourlyWeatherForecastFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BallParkHourlyWeatherForecastPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BallParkHourlyWeatherForecast.
   * @param {BallParkHourlyWeatherForecastCreateArgs} args - Arguments to create a BallParkHourlyWeatherForecast.
   * @example
   * // Create one BallParkHourlyWeatherForecast
   * const BallParkHourlyWeatherForecast = await prisma.ballParkHourlyWeatherForecast.create({
   *   data: {
   *     // ... data to create a BallParkHourlyWeatherForecast
   *   }
   * })
   * 
   */
  create<T extends BallParkHourlyWeatherForecastCreateArgs>(args: Prisma.SelectSubset<T, BallParkHourlyWeatherForecastCreateArgs<ExtArgs>>): Prisma.Prisma__BallParkHourlyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkHourlyWeatherForecastPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BallParkHourlyWeatherForecasts.
   * @param {BallParkHourlyWeatherForecastCreateManyArgs} args - Arguments to create many BallParkHourlyWeatherForecasts.
   * @example
   * // Create many BallParkHourlyWeatherForecasts
   * const ballParkHourlyWeatherForecast = await prisma.ballParkHourlyWeatherForecast.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BallParkHourlyWeatherForecastCreateManyArgs>(args?: Prisma.SelectSubset<T, BallParkHourlyWeatherForecastCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a BallParkHourlyWeatherForecast.
   * @param {BallParkHourlyWeatherForecastDeleteArgs} args - Arguments to delete one BallParkHourlyWeatherForecast.
   * @example
   * // Delete one BallParkHourlyWeatherForecast
   * const BallParkHourlyWeatherForecast = await prisma.ballParkHourlyWeatherForecast.delete({
   *   where: {
   *     // ... filter to delete one BallParkHourlyWeatherForecast
   *   }
   * })
   * 
   */
  delete<T extends BallParkHourlyWeatherForecastDeleteArgs>(args: Prisma.SelectSubset<T, BallParkHourlyWeatherForecastDeleteArgs<ExtArgs>>): Prisma.Prisma__BallParkHourlyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkHourlyWeatherForecastPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BallParkHourlyWeatherForecast.
   * @param {BallParkHourlyWeatherForecastUpdateArgs} args - Arguments to update one BallParkHourlyWeatherForecast.
   * @example
   * // Update one BallParkHourlyWeatherForecast
   * const ballParkHourlyWeatherForecast = await prisma.ballParkHourlyWeatherForecast.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BallParkHourlyWeatherForecastUpdateArgs>(args: Prisma.SelectSubset<T, BallParkHourlyWeatherForecastUpdateArgs<ExtArgs>>): Prisma.Prisma__BallParkHourlyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkHourlyWeatherForecastPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BallParkHourlyWeatherForecasts.
   * @param {BallParkHourlyWeatherForecastDeleteManyArgs} args - Arguments to filter BallParkHourlyWeatherForecasts to delete.
   * @example
   * // Delete a few BallParkHourlyWeatherForecasts
   * const { count } = await prisma.ballParkHourlyWeatherForecast.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BallParkHourlyWeatherForecastDeleteManyArgs>(args?: Prisma.SelectSubset<T, BallParkHourlyWeatherForecastDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BallParkHourlyWeatherForecasts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkHourlyWeatherForecastUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BallParkHourlyWeatherForecasts
   * const ballParkHourlyWeatherForecast = await prisma.ballParkHourlyWeatherForecast.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BallParkHourlyWeatherForecastUpdateManyArgs>(args: Prisma.SelectSubset<T, BallParkHourlyWeatherForecastUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one BallParkHourlyWeatherForecast.
   * @param {BallParkHourlyWeatherForecastUpsertArgs} args - Arguments to update or create a BallParkHourlyWeatherForecast.
   * @example
   * // Update or create a BallParkHourlyWeatherForecast
   * const ballParkHourlyWeatherForecast = await prisma.ballParkHourlyWeatherForecast.upsert({
   *   create: {
   *     // ... data to create a BallParkHourlyWeatherForecast
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BallParkHourlyWeatherForecast we want to update
   *   }
   * })
   */
  upsert<T extends BallParkHourlyWeatherForecastUpsertArgs>(args: Prisma.SelectSubset<T, BallParkHourlyWeatherForecastUpsertArgs<ExtArgs>>): Prisma.Prisma__BallParkHourlyWeatherForecastClient<runtime.Types.Result.GetResult<Prisma.$BallParkHourlyWeatherForecastPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BallParkHourlyWeatherForecasts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkHourlyWeatherForecastCountArgs} args - Arguments to filter BallParkHourlyWeatherForecasts to count.
   * @example
   * // Count the number of BallParkHourlyWeatherForecasts
   * const count = await prisma.ballParkHourlyWeatherForecast.count({
   *   where: {
   *     // ... the filter for the BallParkHourlyWeatherForecasts we want to count
   *   }
   * })
  **/
  count<T extends BallParkHourlyWeatherForecastCountArgs>(
    args?: Prisma.Subset<T, BallParkHourlyWeatherForecastCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BallParkHourlyWeatherForecastCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BallParkHourlyWeatherForecast.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkHourlyWeatherForecastAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BallParkHourlyWeatherForecastAggregateArgs>(args: Prisma.Subset<T, BallParkHourlyWeatherForecastAggregateArgs>): Prisma.PrismaPromise<GetBallParkHourlyWeatherForecastAggregateType<T>>

  /**
   * Group by BallParkHourlyWeatherForecast.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BallParkHourlyWeatherForecastGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BallParkHourlyWeatherForecastGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BallParkHourlyWeatherForecastGroupByArgs['orderBy'] }
      : { orderBy?: BallParkHourlyWeatherForecastGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BallParkHourlyWeatherForecastGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBallParkHourlyWeatherForecastGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BallParkHourlyWeatherForecast model
 */
readonly fields: BallParkHourlyWeatherForecastFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BallParkHourlyWeatherForecast.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BallParkHourlyWeatherForecastClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BallParkHourlyWeatherForecast model
 */
export interface BallParkHourlyWeatherForecastFieldRefs {
  readonly id: Prisma.FieldRef<"BallParkHourlyWeatherForecast", 'Int'>
  readonly date: Prisma.FieldRef<"BallParkHourlyWeatherForecast", 'DateTime'>
  readonly weatherCode: Prisma.FieldRef<"BallParkHourlyWeatherForecast", 'Int'>
  readonly temperature: Prisma.FieldRef<"BallParkHourlyWeatherForecast", 'Float'>
  readonly precipitationProbability: Prisma.FieldRef<"BallParkHourlyWeatherForecast", 'Float'>
  readonly rainFall: Prisma.FieldRef<"BallParkHourlyWeatherForecast", 'Float'>
  readonly ballParkId: Prisma.FieldRef<"BallParkHourlyWeatherForecast", 'Int'>
  readonly createdAt: Prisma.FieldRef<"BallParkHourlyWeatherForecast", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"BallParkHourlyWeatherForecast", 'DateTime'>
}
    

// Custom InputTypes
/**
 * BallParkHourlyWeatherForecast findUnique
 */
export type BallParkHourlyWeatherForecastFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkHourlyWeatherForecast
   */
  select?: Prisma.BallParkHourlyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkHourlyWeatherForecast
   */
  omit?: Prisma.BallParkHourlyWeatherForecastOmit<ExtArgs> | null
  /**
   * Filter, which BallParkHourlyWeatherForecast to fetch.
   */
  where: Prisma.BallParkHourlyWeatherForecastWhereUniqueInput
}

/**
 * BallParkHourlyWeatherForecast findUniqueOrThrow
 */
export type BallParkHourlyWeatherForecastFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkHourlyWeatherForecast
   */
  select?: Prisma.BallParkHourlyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkHourlyWeatherForecast
   */
  omit?: Prisma.BallParkHourlyWeatherForecastOmit<ExtArgs> | null
  /**
   * Filter, which BallParkHourlyWeatherForecast to fetch.
   */
  where: Prisma.BallParkHourlyWeatherForecastWhereUniqueInput
}

/**
 * BallParkHourlyWeatherForecast findFirst
 */
export type BallParkHourlyWeatherForecastFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkHourlyWeatherForecast
   */
  select?: Prisma.BallParkHourlyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkHourlyWeatherForecast
   */
  omit?: Prisma.BallParkHourlyWeatherForecastOmit<ExtArgs> | null
  /**
   * Filter, which BallParkHourlyWeatherForecast to fetch.
   */
  where?: Prisma.BallParkHourlyWeatherForecastWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BallParkHourlyWeatherForecasts to fetch.
   */
  orderBy?: Prisma.BallParkHourlyWeatherForecastOrderByWithRelationInput | Prisma.BallParkHourlyWeatherForecastOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BallParkHourlyWeatherForecasts.
   */
  cursor?: Prisma.BallParkHourlyWeatherForecastWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BallParkHourlyWeatherForecasts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BallParkHourlyWeatherForecasts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BallParkHourlyWeatherForecasts.
   */
  distinct?: Prisma.BallParkHourlyWeatherForecastScalarFieldEnum | Prisma.BallParkHourlyWeatherForecastScalarFieldEnum[]
}

/**
 * BallParkHourlyWeatherForecast findFirstOrThrow
 */
export type BallParkHourlyWeatherForecastFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkHourlyWeatherForecast
   */
  select?: Prisma.BallParkHourlyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkHourlyWeatherForecast
   */
  omit?: Prisma.BallParkHourlyWeatherForecastOmit<ExtArgs> | null
  /**
   * Filter, which BallParkHourlyWeatherForecast to fetch.
   */
  where?: Prisma.BallParkHourlyWeatherForecastWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BallParkHourlyWeatherForecasts to fetch.
   */
  orderBy?: Prisma.BallParkHourlyWeatherForecastOrderByWithRelationInput | Prisma.BallParkHourlyWeatherForecastOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BallParkHourlyWeatherForecasts.
   */
  cursor?: Prisma.BallParkHourlyWeatherForecastWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BallParkHourlyWeatherForecasts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BallParkHourlyWeatherForecasts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BallParkHourlyWeatherForecasts.
   */
  distinct?: Prisma.BallParkHourlyWeatherForecastScalarFieldEnum | Prisma.BallParkHourlyWeatherForecastScalarFieldEnum[]
}

/**
 * BallParkHourlyWeatherForecast findMany
 */
export type BallParkHourlyWeatherForecastFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkHourlyWeatherForecast
   */
  select?: Prisma.BallParkHourlyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkHourlyWeatherForecast
   */
  omit?: Prisma.BallParkHourlyWeatherForecastOmit<ExtArgs> | null
  /**
   * Filter, which BallParkHourlyWeatherForecasts to fetch.
   */
  where?: Prisma.BallParkHourlyWeatherForecastWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BallParkHourlyWeatherForecasts to fetch.
   */
  orderBy?: Prisma.BallParkHourlyWeatherForecastOrderByWithRelationInput | Prisma.BallParkHourlyWeatherForecastOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BallParkHourlyWeatherForecasts.
   */
  cursor?: Prisma.BallParkHourlyWeatherForecastWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BallParkHourlyWeatherForecasts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BallParkHourlyWeatherForecasts.
   */
  skip?: number
  distinct?: Prisma.BallParkHourlyWeatherForecastScalarFieldEnum | Prisma.BallParkHourlyWeatherForecastScalarFieldEnum[]
}

/**
 * BallParkHourlyWeatherForecast create
 */
export type BallParkHourlyWeatherForecastCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkHourlyWeatherForecast
   */
  select?: Prisma.BallParkHourlyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkHourlyWeatherForecast
   */
  omit?: Prisma.BallParkHourlyWeatherForecastOmit<ExtArgs> | null
  /**
   * The data needed to create a BallParkHourlyWeatherForecast.
   */
  data: Prisma.XOR<Prisma.BallParkHourlyWeatherForecastCreateInput, Prisma.BallParkHourlyWeatherForecastUncheckedCreateInput>
}

/**
 * BallParkHourlyWeatherForecast createMany
 */
export type BallParkHourlyWeatherForecastCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BallParkHourlyWeatherForecasts.
   */
  data: Prisma.BallParkHourlyWeatherForecastCreateManyInput | Prisma.BallParkHourlyWeatherForecastCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BallParkHourlyWeatherForecast update
 */
export type BallParkHourlyWeatherForecastUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkHourlyWeatherForecast
   */
  select?: Prisma.BallParkHourlyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkHourlyWeatherForecast
   */
  omit?: Prisma.BallParkHourlyWeatherForecastOmit<ExtArgs> | null
  /**
   * The data needed to update a BallParkHourlyWeatherForecast.
   */
  data: Prisma.XOR<Prisma.BallParkHourlyWeatherForecastUpdateInput, Prisma.BallParkHourlyWeatherForecastUncheckedUpdateInput>
  /**
   * Choose, which BallParkHourlyWeatherForecast to update.
   */
  where: Prisma.BallParkHourlyWeatherForecastWhereUniqueInput
}

/**
 * BallParkHourlyWeatherForecast updateMany
 */
export type BallParkHourlyWeatherForecastUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BallParkHourlyWeatherForecasts.
   */
  data: Prisma.XOR<Prisma.BallParkHourlyWeatherForecastUpdateManyMutationInput, Prisma.BallParkHourlyWeatherForecastUncheckedUpdateManyInput>
  /**
   * Filter which BallParkHourlyWeatherForecasts to update
   */
  where?: Prisma.BallParkHourlyWeatherForecastWhereInput
  /**
   * Limit how many BallParkHourlyWeatherForecasts to update.
   */
  limit?: number
}

/**
 * BallParkHourlyWeatherForecast upsert
 */
export type BallParkHourlyWeatherForecastUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkHourlyWeatherForecast
   */
  select?: Prisma.BallParkHourlyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkHourlyWeatherForecast
   */
  omit?: Prisma.BallParkHourlyWeatherForecastOmit<ExtArgs> | null
  /**
   * The filter to search for the BallParkHourlyWeatherForecast to update in case it exists.
   */
  where: Prisma.BallParkHourlyWeatherForecastWhereUniqueInput
  /**
   * In case the BallParkHourlyWeatherForecast found by the `where` argument doesn't exist, create a new BallParkHourlyWeatherForecast with this data.
   */
  create: Prisma.XOR<Prisma.BallParkHourlyWeatherForecastCreateInput, Prisma.BallParkHourlyWeatherForecastUncheckedCreateInput>
  /**
   * In case the BallParkHourlyWeatherForecast was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BallParkHourlyWeatherForecastUpdateInput, Prisma.BallParkHourlyWeatherForecastUncheckedUpdateInput>
}

/**
 * BallParkHourlyWeatherForecast delete
 */
export type BallParkHourlyWeatherForecastDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkHourlyWeatherForecast
   */
  select?: Prisma.BallParkHourlyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkHourlyWeatherForecast
   */
  omit?: Prisma.BallParkHourlyWeatherForecastOmit<ExtArgs> | null
  /**
   * Filter which BallParkHourlyWeatherForecast to delete.
   */
  where: Prisma.BallParkHourlyWeatherForecastWhereUniqueInput
}

/**
 * BallParkHourlyWeatherForecast deleteMany
 */
export type BallParkHourlyWeatherForecastDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BallParkHourlyWeatherForecasts to delete
   */
  where?: Prisma.BallParkHourlyWeatherForecastWhereInput
  /**
   * Limit how many BallParkHourlyWeatherForecasts to delete.
   */
  limit?: number
}

/**
 * BallParkHourlyWeatherForecast without action
 */
export type BallParkHourlyWeatherForecastDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BallParkHourlyWeatherForecast
   */
  select?: Prisma.BallParkHourlyWeatherForecastSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BallParkHourlyWeatherForecast
   */
  omit?: Prisma.BallParkHourlyWeatherForecastOmit<ExtArgs> | null
}
