/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `CancellationModel` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.ts";
import type * as Prisma from "../internal/prismaNamespace.ts";

/**
 * Model CancellationModel
 *
 */
export type CancellationModelModel =
  runtime.Types.Result.DefaultSelection<Prisma.$CancellationModelPayload>;

export type AggregateCancellationModel = {
  _count: CancellationModelCountAggregateOutputType | null;
  _avg: CancellationModelAvgAggregateOutputType | null;
  _sum: CancellationModelSumAggregateOutputType | null;
  _min: CancellationModelMinAggregateOutputType | null;
  _max: CancellationModelMaxAggregateOutputType | null;
};

export type CancellationModelAvgAggregateOutputType = {
  intercept: number | null;
};

export type CancellationModelSumAggregateOutputType = {
  intercept: number | null;
};

export type CancellationModelMinAggregateOutputType = {
  id: string | null;
  version: string | null;
  intercept: number | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type CancellationModelMaxAggregateOutputType = {
  id: string | null;
  version: string | null;
  intercept: number | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type CancellationModelCountAggregateOutputType = {
  id: number;
  version: number;
  featureOrder: number;
  coefficients: number;
  intercept: number;
  metadata: number;
  createdAt: number;
  updatedAt: number;
  _all: number;
};

export type CancellationModelAvgAggregateInputType = {
  intercept?: true;
};

export type CancellationModelSumAggregateInputType = {
  intercept?: true;
};

export type CancellationModelMinAggregateInputType = {
  id?: true;
  version?: true;
  intercept?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type CancellationModelMaxAggregateInputType = {
  id?: true;
  version?: true;
  intercept?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type CancellationModelCountAggregateInputType = {
  id?: true;
  version?: true;
  featureOrder?: true;
  coefficients?: true;
  intercept?: true;
  metadata?: true;
  createdAt?: true;
  updatedAt?: true;
  _all?: true;
};

export type CancellationModelAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Filter which CancellationModel to aggregate.
   */
  where?: Prisma.CancellationModelWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CancellationModels to fetch.
   */
  orderBy?:
    | Prisma.CancellationModelOrderByWithRelationInput
    | Prisma.CancellationModelOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.CancellationModelWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CancellationModels from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CancellationModels.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned CancellationModels
   **/
  _count?: true | CancellationModelCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: CancellationModelAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: CancellationModelSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: CancellationModelMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: CancellationModelMaxAggregateInputType;
};

export type GetCancellationModelAggregateType<
  T extends CancellationModelAggregateArgs
> = {
  [P in keyof T & keyof AggregateCancellationModel]: P extends
    | "_count"
    | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCancellationModel[P]>
    : Prisma.GetScalarType<T[P], AggregateCancellationModel[P]>;
};

export type CancellationModelGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  where?: Prisma.CancellationModelWhereInput;
  orderBy?:
    | Prisma.CancellationModelOrderByWithAggregationInput
    | Prisma.CancellationModelOrderByWithAggregationInput[];
  by:
    | Prisma.CancellationModelScalarFieldEnum[]
    | Prisma.CancellationModelScalarFieldEnum;
  having?: Prisma.CancellationModelScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: CancellationModelCountAggregateInputType | true;
  _avg?: CancellationModelAvgAggregateInputType;
  _sum?: CancellationModelSumAggregateInputType;
  _min?: CancellationModelMinAggregateInputType;
  _max?: CancellationModelMaxAggregateInputType;
};

export type CancellationModelGroupByOutputType = {
  id: string;
  version: string;
  featureOrder: runtime.JsonValue;
  coefficients: runtime.JsonValue;
  intercept: number;
  metadata: runtime.JsonValue | null;
  createdAt: Date;
  updatedAt: Date;
  _count: CancellationModelCountAggregateOutputType | null;
  _avg: CancellationModelAvgAggregateOutputType | null;
  _sum: CancellationModelSumAggregateOutputType | null;
  _min: CancellationModelMinAggregateOutputType | null;
  _max: CancellationModelMaxAggregateOutputType | null;
};

type GetCancellationModelGroupByPayload<
  T extends CancellationModelGroupByArgs
> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CancellationModelGroupByOutputType, T["by"]> & {
      [P in keyof T &
        keyof CancellationModelGroupByOutputType]: P extends "_count"
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], CancellationModelGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], CancellationModelGroupByOutputType[P]>;
    }
  >
>;

export type CancellationModelWhereInput = {
  AND?:
    | Prisma.CancellationModelWhereInput
    | Prisma.CancellationModelWhereInput[];
  OR?: Prisma.CancellationModelWhereInput[];
  NOT?:
    | Prisma.CancellationModelWhereInput
    | Prisma.CancellationModelWhereInput[];
  id?: Prisma.StringFilter<"CancellationModel"> | string;
  version?: Prisma.StringFilter<"CancellationModel"> | string;
  featureOrder?: Prisma.JsonFilter<"CancellationModel">;
  coefficients?: Prisma.JsonFilter<"CancellationModel">;
  intercept?: Prisma.FloatFilter<"CancellationModel"> | number;
  metadata?: Prisma.JsonNullableFilter<"CancellationModel">;
  createdAt?: Prisma.DateTimeFilter<"CancellationModel"> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<"CancellationModel"> | Date | string;
};

export type CancellationModelOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  featureOrder?: Prisma.SortOrder;
  coefficients?: Prisma.SortOrder;
  intercept?: Prisma.SortOrder;
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  _relevance?: Prisma.CancellationModelOrderByRelevanceInput;
};

export type CancellationModelWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    version?: string;
    AND?:
      | Prisma.CancellationModelWhereInput
      | Prisma.CancellationModelWhereInput[];
    OR?: Prisma.CancellationModelWhereInput[];
    NOT?:
      | Prisma.CancellationModelWhereInput
      | Prisma.CancellationModelWhereInput[];
    featureOrder?: Prisma.JsonFilter<"CancellationModel">;
    coefficients?: Prisma.JsonFilter<"CancellationModel">;
    intercept?: Prisma.FloatFilter<"CancellationModel"> | number;
    metadata?: Prisma.JsonNullableFilter<"CancellationModel">;
    createdAt?: Prisma.DateTimeFilter<"CancellationModel"> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<"CancellationModel"> | Date | string;
  },
  "id" | "version"
>;

export type CancellationModelOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  featureOrder?: Prisma.SortOrder;
  coefficients?: Prisma.SortOrder;
  intercept?: Prisma.SortOrder;
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  _count?: Prisma.CancellationModelCountOrderByAggregateInput;
  _avg?: Prisma.CancellationModelAvgOrderByAggregateInput;
  _max?: Prisma.CancellationModelMaxOrderByAggregateInput;
  _min?: Prisma.CancellationModelMinOrderByAggregateInput;
  _sum?: Prisma.CancellationModelSumOrderByAggregateInput;
};

export type CancellationModelScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.CancellationModelScalarWhereWithAggregatesInput
    | Prisma.CancellationModelScalarWhereWithAggregatesInput[];
  OR?: Prisma.CancellationModelScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.CancellationModelScalarWhereWithAggregatesInput
    | Prisma.CancellationModelScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<"CancellationModel"> | string;
  version?: Prisma.StringWithAggregatesFilter<"CancellationModel"> | string;
  featureOrder?: Prisma.JsonWithAggregatesFilter<"CancellationModel">;
  coefficients?: Prisma.JsonWithAggregatesFilter<"CancellationModel">;
  intercept?: Prisma.FloatWithAggregatesFilter<"CancellationModel"> | number;
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"CancellationModel">;
  createdAt?:
    | Prisma.DateTimeWithAggregatesFilter<"CancellationModel">
    | Date
    | string;
  updatedAt?:
    | Prisma.DateTimeWithAggregatesFilter<"CancellationModel">
    | Date
    | string;
};

export type CancellationModelCreateInput = {
  id?: string;
  version: string;
  featureOrder: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  coefficients: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  intercept: number;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type CancellationModelUncheckedCreateInput = {
  id?: string;
  version: string;
  featureOrder: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  coefficients: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  intercept: number;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type CancellationModelUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  version?: Prisma.StringFieldUpdateOperationsInput | string;
  featureOrder?: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  coefficients?: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  intercept?: Prisma.FloatFieldUpdateOperationsInput | number;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CancellationModelUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  version?: Prisma.StringFieldUpdateOperationsInput | string;
  featureOrder?: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  coefficients?: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  intercept?: Prisma.FloatFieldUpdateOperationsInput | number;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CancellationModelCreateManyInput = {
  id?: string;
  version: string;
  featureOrder: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  coefficients: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  intercept: number;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type CancellationModelUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  version?: Prisma.StringFieldUpdateOperationsInput | string;
  featureOrder?: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  coefficients?: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  intercept?: Prisma.FloatFieldUpdateOperationsInput | number;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CancellationModelUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  version?: Prisma.StringFieldUpdateOperationsInput | string;
  featureOrder?: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  coefficients?: Prisma.JsonNullValueInput | runtime.InputJsonValue;
  intercept?: Prisma.FloatFieldUpdateOperationsInput | number;
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CancellationModelOrderByRelevanceInput = {
  fields:
    | Prisma.CancellationModelOrderByRelevanceFieldEnum
    | Prisma.CancellationModelOrderByRelevanceFieldEnum[];
  sort: Prisma.SortOrder;
  search: string;
};

export type CancellationModelCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  featureOrder?: Prisma.SortOrder;
  coefficients?: Prisma.SortOrder;
  intercept?: Prisma.SortOrder;
  metadata?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type CancellationModelAvgOrderByAggregateInput = {
  intercept?: Prisma.SortOrder;
};

export type CancellationModelMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  intercept?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type CancellationModelMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  intercept?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type CancellationModelSumOrderByAggregateInput = {
  intercept?: Prisma.SortOrder;
};

export type CancellationModelSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    version?: boolean;
    featureOrder?: boolean;
    coefficients?: boolean;
    intercept?: boolean;
    metadata?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
  },
  ExtArgs["result"]["cancellationModel"]
>;

export type CancellationModelSelectScalar = {
  id?: boolean;
  version?: boolean;
  featureOrder?: boolean;
  coefficients?: boolean;
  intercept?: boolean;
  metadata?: boolean;
  createdAt?: boolean;
  updatedAt?: boolean;
};

export type CancellationModelOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetOmit<
  | "id"
  | "version"
  | "featureOrder"
  | "coefficients"
  | "intercept"
  | "metadata"
  | "createdAt"
  | "updatedAt",
  ExtArgs["result"]["cancellationModel"]
>;

export type $CancellationModelPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  name: "CancellationModel";
  objects: {};
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      version: string;
      featureOrder: runtime.JsonValue;
      coefficients: runtime.JsonValue;
      intercept: number;
      metadata: runtime.JsonValue | null;
      createdAt: Date;
      updatedAt: Date;
    },
    ExtArgs["result"]["cancellationModel"]
  >;
  composites: {};
};

export type CancellationModelGetPayload<
  S extends boolean | null | undefined | CancellationModelDefaultArgs
> = runtime.Types.Result.GetResult<Prisma.$CancellationModelPayload, S>;

export type CancellationModelCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = Omit<
  CancellationModelFindManyArgs,
  "select" | "include" | "distinct" | "omit"
> & {
  select?: CancellationModelCountAggregateInputType | true;
};

export interface CancellationModelDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {}
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["CancellationModel"];
    meta: { name: "CancellationModel" };
  };
  /**
   * Find zero or one CancellationModel that matches the filter.
   * @param {CancellationModelFindUniqueArgs} args - Arguments to find a CancellationModel
   * @example
   * // Get one CancellationModel
   * const cancellationModel = await prisma.cancellationModel.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CancellationModelFindUniqueArgs>(
    args: Prisma.SelectSubset<T, CancellationModelFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__CancellationModelClient<
    runtime.Types.Result.GetResult<
      Prisma.$CancellationModelPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one CancellationModel that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CancellationModelFindUniqueOrThrowArgs} args - Arguments to find a CancellationModel
   * @example
   * // Get one CancellationModel
   * const cancellationModel = await prisma.cancellationModel.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CancellationModelFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<
      T,
      CancellationModelFindUniqueOrThrowArgs<ExtArgs>
    >
  ): Prisma.Prisma__CancellationModelClient<
    runtime.Types.Result.GetResult<
      Prisma.$CancellationModelPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first CancellationModel that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CancellationModelFindFirstArgs} args - Arguments to find a CancellationModel
   * @example
   * // Get one CancellationModel
   * const cancellationModel = await prisma.cancellationModel.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CancellationModelFindFirstArgs>(
    args?: Prisma.SelectSubset<T, CancellationModelFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__CancellationModelClient<
    runtime.Types.Result.GetResult<
      Prisma.$CancellationModelPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first CancellationModel that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CancellationModelFindFirstOrThrowArgs} args - Arguments to find a CancellationModel
   * @example
   * // Get one CancellationModel
   * const cancellationModel = await prisma.cancellationModel.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CancellationModelFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<
      T,
      CancellationModelFindFirstOrThrowArgs<ExtArgs>
    >
  ): Prisma.Prisma__CancellationModelClient<
    runtime.Types.Result.GetResult<
      Prisma.$CancellationModelPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more CancellationModels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CancellationModelFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CancellationModels
   * const cancellationModels = await prisma.cancellationModel.findMany()
   *
   * // Get first 10 CancellationModels
   * const cancellationModels = await prisma.cancellationModel.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const cancellationModelWithIdOnly = await prisma.cancellationModel.findMany({ select: { id: true } })
   *
   */
  findMany<T extends CancellationModelFindManyArgs>(
    args?: Prisma.SelectSubset<T, CancellationModelFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$CancellationModelPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >;

  /**
   * Create a CancellationModel.
   * @param {CancellationModelCreateArgs} args - Arguments to create a CancellationModel.
   * @example
   * // Create one CancellationModel
   * const CancellationModel = await prisma.cancellationModel.create({
   *   data: {
   *     // ... data to create a CancellationModel
   *   }
   * })
   *
   */
  create<T extends CancellationModelCreateArgs>(
    args: Prisma.SelectSubset<T, CancellationModelCreateArgs<ExtArgs>>
  ): Prisma.Prisma__CancellationModelClient<
    runtime.Types.Result.GetResult<
      Prisma.$CancellationModelPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many CancellationModels.
   * @param {CancellationModelCreateManyArgs} args - Arguments to create many CancellationModels.
   * @example
   * // Create many CancellationModels
   * const cancellationModel = await prisma.cancellationModel.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends CancellationModelCreateManyArgs>(
    args?: Prisma.SelectSubset<T, CancellationModelCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Delete a CancellationModel.
   * @param {CancellationModelDeleteArgs} args - Arguments to delete one CancellationModel.
   * @example
   * // Delete one CancellationModel
   * const CancellationModel = await prisma.cancellationModel.delete({
   *   where: {
   *     // ... filter to delete one CancellationModel
   *   }
   * })
   *
   */
  delete<T extends CancellationModelDeleteArgs>(
    args: Prisma.SelectSubset<T, CancellationModelDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__CancellationModelClient<
    runtime.Types.Result.GetResult<
      Prisma.$CancellationModelPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one CancellationModel.
   * @param {CancellationModelUpdateArgs} args - Arguments to update one CancellationModel.
   * @example
   * // Update one CancellationModel
   * const cancellationModel = await prisma.cancellationModel.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends CancellationModelUpdateArgs>(
    args: Prisma.SelectSubset<T, CancellationModelUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__CancellationModelClient<
    runtime.Types.Result.GetResult<
      Prisma.$CancellationModelPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more CancellationModels.
   * @param {CancellationModelDeleteManyArgs} args - Arguments to filter CancellationModels to delete.
   * @example
   * // Delete a few CancellationModels
   * const { count } = await prisma.cancellationModel.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends CancellationModelDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, CancellationModelDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more CancellationModels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CancellationModelUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CancellationModels
   * const cancellationModel = await prisma.cancellationModel.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends CancellationModelUpdateManyArgs>(
    args: Prisma.SelectSubset<T, CancellationModelUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create or update one CancellationModel.
   * @param {CancellationModelUpsertArgs} args - Arguments to update or create a CancellationModel.
   * @example
   * // Update or create a CancellationModel
   * const cancellationModel = await prisma.cancellationModel.upsert({
   *   create: {
   *     // ... data to create a CancellationModel
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CancellationModel we want to update
   *   }
   * })
   */
  upsert<T extends CancellationModelUpsertArgs>(
    args: Prisma.SelectSubset<T, CancellationModelUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__CancellationModelClient<
    runtime.Types.Result.GetResult<
      Prisma.$CancellationModelPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of CancellationModels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CancellationModelCountArgs} args - Arguments to filter CancellationModels to count.
   * @example
   * // Count the number of CancellationModels
   * const count = await prisma.cancellationModel.count({
   *   where: {
   *     // ... the filter for the CancellationModels we want to count
   *   }
   * })
   **/
  count<T extends CancellationModelCountArgs>(
    args?: Prisma.Subset<T, CancellationModelCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<
            T["select"],
            CancellationModelCountAggregateOutputType
          >
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a CancellationModel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CancellationModelAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends CancellationModelAggregateArgs>(
    args: Prisma.Subset<T, CancellationModelAggregateArgs>
  ): Prisma.PrismaPromise<GetCancellationModelAggregateType<T>>;

  /**
   * Group by CancellationModel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CancellationModelGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends CancellationModelGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CancellationModelGroupByArgs["orderBy"] }
      : { orderBy?: CancellationModelGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
            ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
            : [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : "take" extends Prisma.Keys<T>
      ? "orderBy" extends Prisma.Keys<T>
        ? ByValid extends Prisma.True
          ? {}
          : {
              [P in OrderFields]: P extends ByFields
                ? never
                : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
            }[OrderFields]
        : 'Error: If you provide "take", you also need to provide "orderBy"'
      : "skip" extends Prisma.Keys<T>
      ? "orderBy" extends Prisma.Keys<T>
        ? ByValid extends Prisma.True
          ? {}
          : {
              [P in OrderFields]: P extends ByFields
                ? never
                : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
            }[OrderFields]
        : 'Error: If you provide "skip", you also need to provide "orderBy"'
      : ByValid extends Prisma.True
      ? {}
      : {
          [P in OrderFields]: P extends ByFields
            ? never
            : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
        }[OrderFields]
  >(
    args: Prisma.SubsetIntersection<
      T,
      CancellationModelGroupByArgs,
      OrderByArg
    > &
      InputErrors
  ): {} extends InputErrors
    ? GetCancellationModelGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the CancellationModel model
   */
  readonly fields: CancellationModelFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CancellationModel.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CancellationModelClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {}
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the CancellationModel model
 */
export interface CancellationModelFieldRefs {
  readonly id: Prisma.FieldRef<"CancellationModel", "String">;
  readonly version: Prisma.FieldRef<"CancellationModel", "String">;
  readonly featureOrder: Prisma.FieldRef<"CancellationModel", "Json">;
  readonly coefficients: Prisma.FieldRef<"CancellationModel", "Json">;
  readonly intercept: Prisma.FieldRef<"CancellationModel", "Float">;
  readonly metadata: Prisma.FieldRef<"CancellationModel", "Json">;
  readonly createdAt: Prisma.FieldRef<"CancellationModel", "DateTime">;
  readonly updatedAt: Prisma.FieldRef<"CancellationModel", "DateTime">;
}

// Custom InputTypes
/**
 * CancellationModel findUnique
 */
export type CancellationModelFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the CancellationModel
   */
  select?: Prisma.CancellationModelSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CancellationModel
   */
  omit?: Prisma.CancellationModelOmit<ExtArgs> | null;
  /**
   * Filter, which CancellationModel to fetch.
   */
  where: Prisma.CancellationModelWhereUniqueInput;
};

/**
 * CancellationModel findUniqueOrThrow
 */
export type CancellationModelFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the CancellationModel
   */
  select?: Prisma.CancellationModelSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CancellationModel
   */
  omit?: Prisma.CancellationModelOmit<ExtArgs> | null;
  /**
   * Filter, which CancellationModel to fetch.
   */
  where: Prisma.CancellationModelWhereUniqueInput;
};

/**
 * CancellationModel findFirst
 */
export type CancellationModelFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the CancellationModel
   */
  select?: Prisma.CancellationModelSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CancellationModel
   */
  omit?: Prisma.CancellationModelOmit<ExtArgs> | null;
  /**
   * Filter, which CancellationModel to fetch.
   */
  where?: Prisma.CancellationModelWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CancellationModels to fetch.
   */
  orderBy?:
    | Prisma.CancellationModelOrderByWithRelationInput
    | Prisma.CancellationModelOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for CancellationModels.
   */
  cursor?: Prisma.CancellationModelWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CancellationModels from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CancellationModels.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of CancellationModels.
   */
  distinct?:
    | Prisma.CancellationModelScalarFieldEnum
    | Prisma.CancellationModelScalarFieldEnum[];
};

/**
 * CancellationModel findFirstOrThrow
 */
export type CancellationModelFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the CancellationModel
   */
  select?: Prisma.CancellationModelSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CancellationModel
   */
  omit?: Prisma.CancellationModelOmit<ExtArgs> | null;
  /**
   * Filter, which CancellationModel to fetch.
   */
  where?: Prisma.CancellationModelWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CancellationModels to fetch.
   */
  orderBy?:
    | Prisma.CancellationModelOrderByWithRelationInput
    | Prisma.CancellationModelOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for CancellationModels.
   */
  cursor?: Prisma.CancellationModelWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CancellationModels from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CancellationModels.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of CancellationModels.
   */
  distinct?:
    | Prisma.CancellationModelScalarFieldEnum
    | Prisma.CancellationModelScalarFieldEnum[];
};

/**
 * CancellationModel findMany
 */
export type CancellationModelFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the CancellationModel
   */
  select?: Prisma.CancellationModelSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CancellationModel
   */
  omit?: Prisma.CancellationModelOmit<ExtArgs> | null;
  /**
   * Filter, which CancellationModels to fetch.
   */
  where?: Prisma.CancellationModelWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CancellationModels to fetch.
   */
  orderBy?:
    | Prisma.CancellationModelOrderByWithRelationInput
    | Prisma.CancellationModelOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing CancellationModels.
   */
  cursor?: Prisma.CancellationModelWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CancellationModels from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CancellationModels.
   */
  skip?: number;
  distinct?:
    | Prisma.CancellationModelScalarFieldEnum
    | Prisma.CancellationModelScalarFieldEnum[];
};

/**
 * CancellationModel create
 */
export type CancellationModelCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the CancellationModel
   */
  select?: Prisma.CancellationModelSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CancellationModel
   */
  omit?: Prisma.CancellationModelOmit<ExtArgs> | null;
  /**
   * The data needed to create a CancellationModel.
   */
  data: Prisma.XOR<
    Prisma.CancellationModelCreateInput,
    Prisma.CancellationModelUncheckedCreateInput
  >;
};

/**
 * CancellationModel createMany
 */
export type CancellationModelCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * The data used to create many CancellationModels.
   */
  data:
    | Prisma.CancellationModelCreateManyInput
    | Prisma.CancellationModelCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * CancellationModel update
 */
export type CancellationModelUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the CancellationModel
   */
  select?: Prisma.CancellationModelSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CancellationModel
   */
  omit?: Prisma.CancellationModelOmit<ExtArgs> | null;
  /**
   * The data needed to update a CancellationModel.
   */
  data: Prisma.XOR<
    Prisma.CancellationModelUpdateInput,
    Prisma.CancellationModelUncheckedUpdateInput
  >;
  /**
   * Choose, which CancellationModel to update.
   */
  where: Prisma.CancellationModelWhereUniqueInput;
};

/**
 * CancellationModel updateMany
 */
export type CancellationModelUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * The data used to update CancellationModels.
   */
  data: Prisma.XOR<
    Prisma.CancellationModelUpdateManyMutationInput,
    Prisma.CancellationModelUncheckedUpdateManyInput
  >;
  /**
   * Filter which CancellationModels to update
   */
  where?: Prisma.CancellationModelWhereInput;
  /**
   * Limit how many CancellationModels to update.
   */
  limit?: number;
};

/**
 * CancellationModel upsert
 */
export type CancellationModelUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the CancellationModel
   */
  select?: Prisma.CancellationModelSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CancellationModel
   */
  omit?: Prisma.CancellationModelOmit<ExtArgs> | null;
  /**
   * The filter to search for the CancellationModel to update in case it exists.
   */
  where: Prisma.CancellationModelWhereUniqueInput;
  /**
   * In case the CancellationModel found by the `where` argument doesn't exist, create a new CancellationModel with this data.
   */
  create: Prisma.XOR<
    Prisma.CancellationModelCreateInput,
    Prisma.CancellationModelUncheckedCreateInput
  >;
  /**
   * In case the CancellationModel was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.CancellationModelUpdateInput,
    Prisma.CancellationModelUncheckedUpdateInput
  >;
};

/**
 * CancellationModel delete
 */
export type CancellationModelDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the CancellationModel
   */
  select?: Prisma.CancellationModelSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CancellationModel
   */
  omit?: Prisma.CancellationModelOmit<ExtArgs> | null;
  /**
   * Filter which CancellationModel to delete.
   */
  where: Prisma.CancellationModelWhereUniqueInput;
};

/**
 * CancellationModel deleteMany
 */
export type CancellationModelDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Filter which CancellationModels to delete
   */
  where?: Prisma.CancellationModelWhereInput;
  /**
   * Limit how many CancellationModels to delete.
   */
  limit?: number;
};

/**
 * CancellationModel without action
 */
export type CancellationModelDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the CancellationModel
   */
  select?: Prisma.CancellationModelSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CancellationModel
   */
  omit?: Prisma.CancellationModelOmit<ExtArgs> | null;
};
