
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PastGameRecord` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model PastGameRecord
 * 
 */
export type PastGameRecordModel = runtime.Types.Result.DefaultSelection<Prisma.$PastGameRecordPayload>

export type AggregatePastGameRecord = {
  _count: PastGameRecordCountAggregateOutputType | null
  _avg: PastGameRecordAvgAggregateOutputType | null
  _sum: PastGameRecordSumAggregateOutputType | null
  _min: PastGameRecordMinAggregateOutputType | null
  _max: PastGameRecordMaxAggregateOutputType | null
}

export type PastGameRecordAvgAggregateOutputType = {
  id: number | null
}

export type PastGameRecordSumAggregateOutputType = {
  id: number | null
}

export type PastGameRecordMinAggregateOutputType = {
  id: number | null
  date: Date | null
  homeTeam: string | null
  awayTeam: string | null
  ballPark: string | null
  cancelled: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PastGameRecordMaxAggregateOutputType = {
  id: number | null
  date: Date | null
  homeTeam: string | null
  awayTeam: string | null
  ballPark: string | null
  cancelled: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PastGameRecordCountAggregateOutputType = {
  id: number
  date: number
  homeTeam: number
  awayTeam: number
  ballPark: number
  cancelled: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PastGameRecordAvgAggregateInputType = {
  id?: true
}

export type PastGameRecordSumAggregateInputType = {
  id?: true
}

export type PastGameRecordMinAggregateInputType = {
  id?: true
  date?: true
  homeTeam?: true
  awayTeam?: true
  ballPark?: true
  cancelled?: true
  createdAt?: true
  updatedAt?: true
}

export type PastGameRecordMaxAggregateInputType = {
  id?: true
  date?: true
  homeTeam?: true
  awayTeam?: true
  ballPark?: true
  cancelled?: true
  createdAt?: true
  updatedAt?: true
}

export type PastGameRecordCountAggregateInputType = {
  id?: true
  date?: true
  homeTeam?: true
  awayTeam?: true
  ballPark?: true
  cancelled?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PastGameRecordAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PastGameRecord to aggregate.
   */
  where?: Prisma.PastGameRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PastGameRecords to fetch.
   */
  orderBy?: Prisma.PastGameRecordOrderByWithRelationInput | Prisma.PastGameRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PastGameRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PastGameRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PastGameRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PastGameRecords
  **/
  _count?: true | PastGameRecordCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PastGameRecordAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PastGameRecordSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PastGameRecordMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PastGameRecordMaxAggregateInputType
}

export type GetPastGameRecordAggregateType<T extends PastGameRecordAggregateArgs> = {
      [P in keyof T & keyof AggregatePastGameRecord]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePastGameRecord[P]>
    : Prisma.GetScalarType<T[P], AggregatePastGameRecord[P]>
}




export type PastGameRecordGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PastGameRecordWhereInput
  orderBy?: Prisma.PastGameRecordOrderByWithAggregationInput | Prisma.PastGameRecordOrderByWithAggregationInput[]
  by: Prisma.PastGameRecordScalarFieldEnum[] | Prisma.PastGameRecordScalarFieldEnum
  having?: Prisma.PastGameRecordScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PastGameRecordCountAggregateInputType | true
  _avg?: PastGameRecordAvgAggregateInputType
  _sum?: PastGameRecordSumAggregateInputType
  _min?: PastGameRecordMinAggregateInputType
  _max?: PastGameRecordMaxAggregateInputType
}

export type PastGameRecordGroupByOutputType = {
  id: number
  date: Date
  homeTeam: string
  awayTeam: string
  ballPark: string
  cancelled: boolean
  createdAt: Date
  updatedAt: Date
  _count: PastGameRecordCountAggregateOutputType | null
  _avg: PastGameRecordAvgAggregateOutputType | null
  _sum: PastGameRecordSumAggregateOutputType | null
  _min: PastGameRecordMinAggregateOutputType | null
  _max: PastGameRecordMaxAggregateOutputType | null
}

type GetPastGameRecordGroupByPayload<T extends PastGameRecordGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PastGameRecordGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PastGameRecordGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PastGameRecordGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PastGameRecordGroupByOutputType[P]>
      }
    >
  >



export type PastGameRecordWhereInput = {
  AND?: Prisma.PastGameRecordWhereInput | Prisma.PastGameRecordWhereInput[]
  OR?: Prisma.PastGameRecordWhereInput[]
  NOT?: Prisma.PastGameRecordWhereInput | Prisma.PastGameRecordWhereInput[]
  id?: Prisma.IntFilter<"PastGameRecord"> | number
  date?: Prisma.DateTimeFilter<"PastGameRecord"> | Date | string
  homeTeam?: Prisma.StringFilter<"PastGameRecord"> | string
  awayTeam?: Prisma.StringFilter<"PastGameRecord"> | string
  ballPark?: Prisma.StringFilter<"PastGameRecord"> | string
  cancelled?: Prisma.BoolFilter<"PastGameRecord"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PastGameRecord"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PastGameRecord"> | Date | string
}

export type PastGameRecordOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  homeTeam?: Prisma.SortOrder
  awayTeam?: Prisma.SortOrder
  ballPark?: Prisma.SortOrder
  cancelled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _relevance?: Prisma.PastGameRecordOrderByRelevanceInput
}

export type PastGameRecordWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  date_homeTeam_awayTeam?: Prisma.PastGameRecordDateHomeTeamAwayTeamCompoundUniqueInput
  AND?: Prisma.PastGameRecordWhereInput | Prisma.PastGameRecordWhereInput[]
  OR?: Prisma.PastGameRecordWhereInput[]
  NOT?: Prisma.PastGameRecordWhereInput | Prisma.PastGameRecordWhereInput[]
  date?: Prisma.DateTimeFilter<"PastGameRecord"> | Date | string
  homeTeam?: Prisma.StringFilter<"PastGameRecord"> | string
  awayTeam?: Prisma.StringFilter<"PastGameRecord"> | string
  ballPark?: Prisma.StringFilter<"PastGameRecord"> | string
  cancelled?: Prisma.BoolFilter<"PastGameRecord"> | boolean
  createdAt?: Prisma.DateTimeFilter<"PastGameRecord"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PastGameRecord"> | Date | string
}, "id" | "date_homeTeam_awayTeam">

export type PastGameRecordOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  homeTeam?: Prisma.SortOrder
  awayTeam?: Prisma.SortOrder
  ballPark?: Prisma.SortOrder
  cancelled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PastGameRecordCountOrderByAggregateInput
  _avg?: Prisma.PastGameRecordAvgOrderByAggregateInput
  _max?: Prisma.PastGameRecordMaxOrderByAggregateInput
  _min?: Prisma.PastGameRecordMinOrderByAggregateInput
  _sum?: Prisma.PastGameRecordSumOrderByAggregateInput
}

export type PastGameRecordScalarWhereWithAggregatesInput = {
  AND?: Prisma.PastGameRecordScalarWhereWithAggregatesInput | Prisma.PastGameRecordScalarWhereWithAggregatesInput[]
  OR?: Prisma.PastGameRecordScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PastGameRecordScalarWhereWithAggregatesInput | Prisma.PastGameRecordScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"PastGameRecord"> | number
  date?: Prisma.DateTimeWithAggregatesFilter<"PastGameRecord"> | Date | string
  homeTeam?: Prisma.StringWithAggregatesFilter<"PastGameRecord"> | string
  awayTeam?: Prisma.StringWithAggregatesFilter<"PastGameRecord"> | string
  ballPark?: Prisma.StringWithAggregatesFilter<"PastGameRecord"> | string
  cancelled?: Prisma.BoolWithAggregatesFilter<"PastGameRecord"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PastGameRecord"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PastGameRecord"> | Date | string
}

export type PastGameRecordCreateInput = {
  date: Date | string
  homeTeam: string
  awayTeam: string
  ballPark: string
  cancelled: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PastGameRecordUncheckedCreateInput = {
  id?: number
  date: Date | string
  homeTeam: string
  awayTeam: string
  ballPark: string
  cancelled: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PastGameRecordUpdateInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  homeTeam?: Prisma.StringFieldUpdateOperationsInput | string
  awayTeam?: Prisma.StringFieldUpdateOperationsInput | string
  ballPark?: Prisma.StringFieldUpdateOperationsInput | string
  cancelled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PastGameRecordUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  homeTeam?: Prisma.StringFieldUpdateOperationsInput | string
  awayTeam?: Prisma.StringFieldUpdateOperationsInput | string
  ballPark?: Prisma.StringFieldUpdateOperationsInput | string
  cancelled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PastGameRecordCreateManyInput = {
  id?: number
  date: Date | string
  homeTeam: string
  awayTeam: string
  ballPark: string
  cancelled: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PastGameRecordUpdateManyMutationInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  homeTeam?: Prisma.StringFieldUpdateOperationsInput | string
  awayTeam?: Prisma.StringFieldUpdateOperationsInput | string
  ballPark?: Prisma.StringFieldUpdateOperationsInput | string
  cancelled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PastGameRecordUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  homeTeam?: Prisma.StringFieldUpdateOperationsInput | string
  awayTeam?: Prisma.StringFieldUpdateOperationsInput | string
  ballPark?: Prisma.StringFieldUpdateOperationsInput | string
  cancelled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PastGameRecordOrderByRelevanceInput = {
  fields: Prisma.PastGameRecordOrderByRelevanceFieldEnum | Prisma.PastGameRecordOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type PastGameRecordDateHomeTeamAwayTeamCompoundUniqueInput = {
  date: Date | string
  homeTeam: string
  awayTeam: string
}

export type PastGameRecordCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  homeTeam?: Prisma.SortOrder
  awayTeam?: Prisma.SortOrder
  ballPark?: Prisma.SortOrder
  cancelled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PastGameRecordAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type PastGameRecordMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  homeTeam?: Prisma.SortOrder
  awayTeam?: Prisma.SortOrder
  ballPark?: Prisma.SortOrder
  cancelled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PastGameRecordMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  homeTeam?: Prisma.SortOrder
  awayTeam?: Prisma.SortOrder
  ballPark?: Prisma.SortOrder
  cancelled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PastGameRecordSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type PastGameRecordSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  homeTeam?: boolean
  awayTeam?: boolean
  ballPark?: boolean
  cancelled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["pastGameRecord"]>



export type PastGameRecordSelectScalar = {
  id?: boolean
  date?: boolean
  homeTeam?: boolean
  awayTeam?: boolean
  ballPark?: boolean
  cancelled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PastGameRecordOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "homeTeam" | "awayTeam" | "ballPark" | "cancelled" | "createdAt" | "updatedAt", ExtArgs["result"]["pastGameRecord"]>

export type $PastGameRecordPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PastGameRecord"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    date: Date
    homeTeam: string
    awayTeam: string
    ballPark: string
    cancelled: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["pastGameRecord"]>
  composites: {}
}

export type PastGameRecordGetPayload<S extends boolean | null | undefined | PastGameRecordDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PastGameRecordPayload, S>

export type PastGameRecordCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PastGameRecordFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PastGameRecordCountAggregateInputType | true
  }

export interface PastGameRecordDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PastGameRecord'], meta: { name: 'PastGameRecord' } }
  /**
   * Find zero or one PastGameRecord that matches the filter.
   * @param {PastGameRecordFindUniqueArgs} args - Arguments to find a PastGameRecord
   * @example
   * // Get one PastGameRecord
   * const pastGameRecord = await prisma.pastGameRecord.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PastGameRecordFindUniqueArgs>(args: Prisma.SelectSubset<T, PastGameRecordFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PastGameRecordClient<runtime.Types.Result.GetResult<Prisma.$PastGameRecordPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PastGameRecord that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PastGameRecordFindUniqueOrThrowArgs} args - Arguments to find a PastGameRecord
   * @example
   * // Get one PastGameRecord
   * const pastGameRecord = await prisma.pastGameRecord.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PastGameRecordFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PastGameRecordFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PastGameRecordClient<runtime.Types.Result.GetResult<Prisma.$PastGameRecordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PastGameRecord that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PastGameRecordFindFirstArgs} args - Arguments to find a PastGameRecord
   * @example
   * // Get one PastGameRecord
   * const pastGameRecord = await prisma.pastGameRecord.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PastGameRecordFindFirstArgs>(args?: Prisma.SelectSubset<T, PastGameRecordFindFirstArgs<ExtArgs>>): Prisma.Prisma__PastGameRecordClient<runtime.Types.Result.GetResult<Prisma.$PastGameRecordPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PastGameRecord that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PastGameRecordFindFirstOrThrowArgs} args - Arguments to find a PastGameRecord
   * @example
   * // Get one PastGameRecord
   * const pastGameRecord = await prisma.pastGameRecord.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PastGameRecordFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PastGameRecordFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PastGameRecordClient<runtime.Types.Result.GetResult<Prisma.$PastGameRecordPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PastGameRecords that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PastGameRecordFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PastGameRecords
   * const pastGameRecords = await prisma.pastGameRecord.findMany()
   * 
   * // Get first 10 PastGameRecords
   * const pastGameRecords = await prisma.pastGameRecord.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pastGameRecordWithIdOnly = await prisma.pastGameRecord.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PastGameRecordFindManyArgs>(args?: Prisma.SelectSubset<T, PastGameRecordFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PastGameRecordPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PastGameRecord.
   * @param {PastGameRecordCreateArgs} args - Arguments to create a PastGameRecord.
   * @example
   * // Create one PastGameRecord
   * const PastGameRecord = await prisma.pastGameRecord.create({
   *   data: {
   *     // ... data to create a PastGameRecord
   *   }
   * })
   * 
   */
  create<T extends PastGameRecordCreateArgs>(args: Prisma.SelectSubset<T, PastGameRecordCreateArgs<ExtArgs>>): Prisma.Prisma__PastGameRecordClient<runtime.Types.Result.GetResult<Prisma.$PastGameRecordPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PastGameRecords.
   * @param {PastGameRecordCreateManyArgs} args - Arguments to create many PastGameRecords.
   * @example
   * // Create many PastGameRecords
   * const pastGameRecord = await prisma.pastGameRecord.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PastGameRecordCreateManyArgs>(args?: Prisma.SelectSubset<T, PastGameRecordCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a PastGameRecord.
   * @param {PastGameRecordDeleteArgs} args - Arguments to delete one PastGameRecord.
   * @example
   * // Delete one PastGameRecord
   * const PastGameRecord = await prisma.pastGameRecord.delete({
   *   where: {
   *     // ... filter to delete one PastGameRecord
   *   }
   * })
   * 
   */
  delete<T extends PastGameRecordDeleteArgs>(args: Prisma.SelectSubset<T, PastGameRecordDeleteArgs<ExtArgs>>): Prisma.Prisma__PastGameRecordClient<runtime.Types.Result.GetResult<Prisma.$PastGameRecordPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PastGameRecord.
   * @param {PastGameRecordUpdateArgs} args - Arguments to update one PastGameRecord.
   * @example
   * // Update one PastGameRecord
   * const pastGameRecord = await prisma.pastGameRecord.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PastGameRecordUpdateArgs>(args: Prisma.SelectSubset<T, PastGameRecordUpdateArgs<ExtArgs>>): Prisma.Prisma__PastGameRecordClient<runtime.Types.Result.GetResult<Prisma.$PastGameRecordPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PastGameRecords.
   * @param {PastGameRecordDeleteManyArgs} args - Arguments to filter PastGameRecords to delete.
   * @example
   * // Delete a few PastGameRecords
   * const { count } = await prisma.pastGameRecord.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PastGameRecordDeleteManyArgs>(args?: Prisma.SelectSubset<T, PastGameRecordDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PastGameRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PastGameRecordUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PastGameRecords
   * const pastGameRecord = await prisma.pastGameRecord.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PastGameRecordUpdateManyArgs>(args: Prisma.SelectSubset<T, PastGameRecordUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one PastGameRecord.
   * @param {PastGameRecordUpsertArgs} args - Arguments to update or create a PastGameRecord.
   * @example
   * // Update or create a PastGameRecord
   * const pastGameRecord = await prisma.pastGameRecord.upsert({
   *   create: {
   *     // ... data to create a PastGameRecord
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PastGameRecord we want to update
   *   }
   * })
   */
  upsert<T extends PastGameRecordUpsertArgs>(args: Prisma.SelectSubset<T, PastGameRecordUpsertArgs<ExtArgs>>): Prisma.Prisma__PastGameRecordClient<runtime.Types.Result.GetResult<Prisma.$PastGameRecordPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PastGameRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PastGameRecordCountArgs} args - Arguments to filter PastGameRecords to count.
   * @example
   * // Count the number of PastGameRecords
   * const count = await prisma.pastGameRecord.count({
   *   where: {
   *     // ... the filter for the PastGameRecords we want to count
   *   }
   * })
  **/
  count<T extends PastGameRecordCountArgs>(
    args?: Prisma.Subset<T, PastGameRecordCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PastGameRecordCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PastGameRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PastGameRecordAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PastGameRecordAggregateArgs>(args: Prisma.Subset<T, PastGameRecordAggregateArgs>): Prisma.PrismaPromise<GetPastGameRecordAggregateType<T>>

  /**
   * Group by PastGameRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PastGameRecordGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PastGameRecordGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PastGameRecordGroupByArgs['orderBy'] }
      : { orderBy?: PastGameRecordGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PastGameRecordGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPastGameRecordGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PastGameRecord model
 */
readonly fields: PastGameRecordFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PastGameRecord.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PastGameRecordClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PastGameRecord model
 */
export interface PastGameRecordFieldRefs {
  readonly id: Prisma.FieldRef<"PastGameRecord", 'Int'>
  readonly date: Prisma.FieldRef<"PastGameRecord", 'DateTime'>
  readonly homeTeam: Prisma.FieldRef<"PastGameRecord", 'String'>
  readonly awayTeam: Prisma.FieldRef<"PastGameRecord", 'String'>
  readonly ballPark: Prisma.FieldRef<"PastGameRecord", 'String'>
  readonly cancelled: Prisma.FieldRef<"PastGameRecord", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"PastGameRecord", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PastGameRecord", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PastGameRecord findUnique
 */
export type PastGameRecordFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PastGameRecord
   */
  select?: Prisma.PastGameRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PastGameRecord
   */
  omit?: Prisma.PastGameRecordOmit<ExtArgs> | null
  /**
   * Filter, which PastGameRecord to fetch.
   */
  where: Prisma.PastGameRecordWhereUniqueInput
}

/**
 * PastGameRecord findUniqueOrThrow
 */
export type PastGameRecordFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PastGameRecord
   */
  select?: Prisma.PastGameRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PastGameRecord
   */
  omit?: Prisma.PastGameRecordOmit<ExtArgs> | null
  /**
   * Filter, which PastGameRecord to fetch.
   */
  where: Prisma.PastGameRecordWhereUniqueInput
}

/**
 * PastGameRecord findFirst
 */
export type PastGameRecordFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PastGameRecord
   */
  select?: Prisma.PastGameRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PastGameRecord
   */
  omit?: Prisma.PastGameRecordOmit<ExtArgs> | null
  /**
   * Filter, which PastGameRecord to fetch.
   */
  where?: Prisma.PastGameRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PastGameRecords to fetch.
   */
  orderBy?: Prisma.PastGameRecordOrderByWithRelationInput | Prisma.PastGameRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PastGameRecords.
   */
  cursor?: Prisma.PastGameRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PastGameRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PastGameRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PastGameRecords.
   */
  distinct?: Prisma.PastGameRecordScalarFieldEnum | Prisma.PastGameRecordScalarFieldEnum[]
}

/**
 * PastGameRecord findFirstOrThrow
 */
export type PastGameRecordFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PastGameRecord
   */
  select?: Prisma.PastGameRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PastGameRecord
   */
  omit?: Prisma.PastGameRecordOmit<ExtArgs> | null
  /**
   * Filter, which PastGameRecord to fetch.
   */
  where?: Prisma.PastGameRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PastGameRecords to fetch.
   */
  orderBy?: Prisma.PastGameRecordOrderByWithRelationInput | Prisma.PastGameRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PastGameRecords.
   */
  cursor?: Prisma.PastGameRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PastGameRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PastGameRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PastGameRecords.
   */
  distinct?: Prisma.PastGameRecordScalarFieldEnum | Prisma.PastGameRecordScalarFieldEnum[]
}

/**
 * PastGameRecord findMany
 */
export type PastGameRecordFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PastGameRecord
   */
  select?: Prisma.PastGameRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PastGameRecord
   */
  omit?: Prisma.PastGameRecordOmit<ExtArgs> | null
  /**
   * Filter, which PastGameRecords to fetch.
   */
  where?: Prisma.PastGameRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PastGameRecords to fetch.
   */
  orderBy?: Prisma.PastGameRecordOrderByWithRelationInput | Prisma.PastGameRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PastGameRecords.
   */
  cursor?: Prisma.PastGameRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PastGameRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PastGameRecords.
   */
  skip?: number
  distinct?: Prisma.PastGameRecordScalarFieldEnum | Prisma.PastGameRecordScalarFieldEnum[]
}

/**
 * PastGameRecord create
 */
export type PastGameRecordCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PastGameRecord
   */
  select?: Prisma.PastGameRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PastGameRecord
   */
  omit?: Prisma.PastGameRecordOmit<ExtArgs> | null
  /**
   * The data needed to create a PastGameRecord.
   */
  data: Prisma.XOR<Prisma.PastGameRecordCreateInput, Prisma.PastGameRecordUncheckedCreateInput>
}

/**
 * PastGameRecord createMany
 */
export type PastGameRecordCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PastGameRecords.
   */
  data: Prisma.PastGameRecordCreateManyInput | Prisma.PastGameRecordCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PastGameRecord update
 */
export type PastGameRecordUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PastGameRecord
   */
  select?: Prisma.PastGameRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PastGameRecord
   */
  omit?: Prisma.PastGameRecordOmit<ExtArgs> | null
  /**
   * The data needed to update a PastGameRecord.
   */
  data: Prisma.XOR<Prisma.PastGameRecordUpdateInput, Prisma.PastGameRecordUncheckedUpdateInput>
  /**
   * Choose, which PastGameRecord to update.
   */
  where: Prisma.PastGameRecordWhereUniqueInput
}

/**
 * PastGameRecord updateMany
 */
export type PastGameRecordUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PastGameRecords.
   */
  data: Prisma.XOR<Prisma.PastGameRecordUpdateManyMutationInput, Prisma.PastGameRecordUncheckedUpdateManyInput>
  /**
   * Filter which PastGameRecords to update
   */
  where?: Prisma.PastGameRecordWhereInput
  /**
   * Limit how many PastGameRecords to update.
   */
  limit?: number
}

/**
 * PastGameRecord upsert
 */
export type PastGameRecordUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PastGameRecord
   */
  select?: Prisma.PastGameRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PastGameRecord
   */
  omit?: Prisma.PastGameRecordOmit<ExtArgs> | null
  /**
   * The filter to search for the PastGameRecord to update in case it exists.
   */
  where: Prisma.PastGameRecordWhereUniqueInput
  /**
   * In case the PastGameRecord found by the `where` argument doesn't exist, create a new PastGameRecord with this data.
   */
  create: Prisma.XOR<Prisma.PastGameRecordCreateInput, Prisma.PastGameRecordUncheckedCreateInput>
  /**
   * In case the PastGameRecord was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PastGameRecordUpdateInput, Prisma.PastGameRecordUncheckedUpdateInput>
}

/**
 * PastGameRecord delete
 */
export type PastGameRecordDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PastGameRecord
   */
  select?: Prisma.PastGameRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PastGameRecord
   */
  omit?: Prisma.PastGameRecordOmit<ExtArgs> | null
  /**
   * Filter which PastGameRecord to delete.
   */
  where: Prisma.PastGameRecordWhereUniqueInput
}

/**
 * PastGameRecord deleteMany
 */
export type PastGameRecordDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PastGameRecords to delete
   */
  where?: Prisma.PastGameRecordWhereInput
  /**
   * Limit how many PastGameRecords to delete.
   */
  limit?: number
}

/**
 * PastGameRecord without action
 */
export type PastGameRecordDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PastGameRecord
   */
  select?: Prisma.PastGameRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PastGameRecord
   */
  omit?: Prisma.PastGameRecordOmit<ExtArgs> | null
}
