
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ScheduledGame` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ScheduledGame
 * 
 */
export type ScheduledGameModel = runtime.Types.Result.DefaultSelection<Prisma.$ScheduledGamePayload>

export type AggregateScheduledGame = {
  _count: ScheduledGameCountAggregateOutputType | null
  _min: ScheduledGameMinAggregateOutputType | null
  _max: ScheduledGameMaxAggregateOutputType | null
}

export type ScheduledGameMinAggregateOutputType = {
  id: string | null
  date: Date | null
  category: string | null
  homeTeam: string | null
  awayTeam: string | null
  ballPark: string | null
  status: $Enums.GameStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ScheduledGameMaxAggregateOutputType = {
  id: string | null
  date: Date | null
  category: string | null
  homeTeam: string | null
  awayTeam: string | null
  ballPark: string | null
  status: $Enums.GameStatus | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ScheduledGameCountAggregateOutputType = {
  id: number
  date: number
  category: number
  homeTeam: number
  awayTeam: number
  ballPark: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ScheduledGameMinAggregateInputType = {
  id?: true
  date?: true
  category?: true
  homeTeam?: true
  awayTeam?: true
  ballPark?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type ScheduledGameMaxAggregateInputType = {
  id?: true
  date?: true
  category?: true
  homeTeam?: true
  awayTeam?: true
  ballPark?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type ScheduledGameCountAggregateInputType = {
  id?: true
  date?: true
  category?: true
  homeTeam?: true
  awayTeam?: true
  ballPark?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ScheduledGameAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ScheduledGame to aggregate.
   */
  where?: Prisma.ScheduledGameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ScheduledGames to fetch.
   */
  orderBy?: Prisma.ScheduledGameOrderByWithRelationInput | Prisma.ScheduledGameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ScheduledGameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ScheduledGames from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ScheduledGames.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ScheduledGames
  **/
  _count?: true | ScheduledGameCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ScheduledGameMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ScheduledGameMaxAggregateInputType
}

export type GetScheduledGameAggregateType<T extends ScheduledGameAggregateArgs> = {
      [P in keyof T & keyof AggregateScheduledGame]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateScheduledGame[P]>
    : Prisma.GetScalarType<T[P], AggregateScheduledGame[P]>
}




export type ScheduledGameGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ScheduledGameWhereInput
  orderBy?: Prisma.ScheduledGameOrderByWithAggregationInput | Prisma.ScheduledGameOrderByWithAggregationInput[]
  by: Prisma.ScheduledGameScalarFieldEnum[] | Prisma.ScheduledGameScalarFieldEnum
  having?: Prisma.ScheduledGameScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ScheduledGameCountAggregateInputType | true
  _min?: ScheduledGameMinAggregateInputType
  _max?: ScheduledGameMaxAggregateInputType
}

export type ScheduledGameGroupByOutputType = {
  id: string
  date: Date
  category: string
  homeTeam: string
  awayTeam: string
  ballPark: string
  status: $Enums.GameStatus
  createdAt: Date
  updatedAt: Date
  _count: ScheduledGameCountAggregateOutputType | null
  _min: ScheduledGameMinAggregateOutputType | null
  _max: ScheduledGameMaxAggregateOutputType | null
}

type GetScheduledGameGroupByPayload<T extends ScheduledGameGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ScheduledGameGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ScheduledGameGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ScheduledGameGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ScheduledGameGroupByOutputType[P]>
      }
    >
  >



export type ScheduledGameWhereInput = {
  AND?: Prisma.ScheduledGameWhereInput | Prisma.ScheduledGameWhereInput[]
  OR?: Prisma.ScheduledGameWhereInput[]
  NOT?: Prisma.ScheduledGameWhereInput | Prisma.ScheduledGameWhereInput[]
  id?: Prisma.StringFilter<"ScheduledGame"> | string
  date?: Prisma.DateTimeFilter<"ScheduledGame"> | Date | string
  category?: Prisma.StringFilter<"ScheduledGame"> | string
  homeTeam?: Prisma.StringFilter<"ScheduledGame"> | string
  awayTeam?: Prisma.StringFilter<"ScheduledGame"> | string
  ballPark?: Prisma.StringFilter<"ScheduledGame"> | string
  status?: Prisma.EnumGameStatusFilter<"ScheduledGame"> | $Enums.GameStatus
  createdAt?: Prisma.DateTimeFilter<"ScheduledGame"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ScheduledGame"> | Date | string
}

export type ScheduledGameOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  category?: Prisma.SortOrder
  homeTeam?: Prisma.SortOrder
  awayTeam?: Prisma.SortOrder
  ballPark?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _relevance?: Prisma.ScheduledGameOrderByRelevanceInput
}

export type ScheduledGameWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ScheduledGameWhereInput | Prisma.ScheduledGameWhereInput[]
  OR?: Prisma.ScheduledGameWhereInput[]
  NOT?: Prisma.ScheduledGameWhereInput | Prisma.ScheduledGameWhereInput[]
  date?: Prisma.DateTimeFilter<"ScheduledGame"> | Date | string
  category?: Prisma.StringFilter<"ScheduledGame"> | string
  homeTeam?: Prisma.StringFilter<"ScheduledGame"> | string
  awayTeam?: Prisma.StringFilter<"ScheduledGame"> | string
  ballPark?: Prisma.StringFilter<"ScheduledGame"> | string
  status?: Prisma.EnumGameStatusFilter<"ScheduledGame"> | $Enums.GameStatus
  createdAt?: Prisma.DateTimeFilter<"ScheduledGame"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ScheduledGame"> | Date | string
}, "id">

export type ScheduledGameOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  category?: Prisma.SortOrder
  homeTeam?: Prisma.SortOrder
  awayTeam?: Prisma.SortOrder
  ballPark?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ScheduledGameCountOrderByAggregateInput
  _max?: Prisma.ScheduledGameMaxOrderByAggregateInput
  _min?: Prisma.ScheduledGameMinOrderByAggregateInput
}

export type ScheduledGameScalarWhereWithAggregatesInput = {
  AND?: Prisma.ScheduledGameScalarWhereWithAggregatesInput | Prisma.ScheduledGameScalarWhereWithAggregatesInput[]
  OR?: Prisma.ScheduledGameScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ScheduledGameScalarWhereWithAggregatesInput | Prisma.ScheduledGameScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ScheduledGame"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"ScheduledGame"> | Date | string
  category?: Prisma.StringWithAggregatesFilter<"ScheduledGame"> | string
  homeTeam?: Prisma.StringWithAggregatesFilter<"ScheduledGame"> | string
  awayTeam?: Prisma.StringWithAggregatesFilter<"ScheduledGame"> | string
  ballPark?: Prisma.StringWithAggregatesFilter<"ScheduledGame"> | string
  status?: Prisma.EnumGameStatusWithAggregatesFilter<"ScheduledGame"> | $Enums.GameStatus
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ScheduledGame"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ScheduledGame"> | Date | string
}

export type ScheduledGameCreateInput = {
  id?: string
  date: Date | string
  category: string
  homeTeam: string
  awayTeam: string
  ballPark: string
  status?: $Enums.GameStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ScheduledGameUncheckedCreateInput = {
  id?: string
  date: Date | string
  category: string
  homeTeam: string
  awayTeam: string
  ballPark: string
  status?: $Enums.GameStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ScheduledGameUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  homeTeam?: Prisma.StringFieldUpdateOperationsInput | string
  awayTeam?: Prisma.StringFieldUpdateOperationsInput | string
  ballPark?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumGameStatusFieldUpdateOperationsInput | $Enums.GameStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ScheduledGameUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  homeTeam?: Prisma.StringFieldUpdateOperationsInput | string
  awayTeam?: Prisma.StringFieldUpdateOperationsInput | string
  ballPark?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumGameStatusFieldUpdateOperationsInput | $Enums.GameStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ScheduledGameCreateManyInput = {
  id?: string
  date: Date | string
  category: string
  homeTeam: string
  awayTeam: string
  ballPark: string
  status?: $Enums.GameStatus
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ScheduledGameUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  homeTeam?: Prisma.StringFieldUpdateOperationsInput | string
  awayTeam?: Prisma.StringFieldUpdateOperationsInput | string
  ballPark?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumGameStatusFieldUpdateOperationsInput | $Enums.GameStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ScheduledGameUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  homeTeam?: Prisma.StringFieldUpdateOperationsInput | string
  awayTeam?: Prisma.StringFieldUpdateOperationsInput | string
  ballPark?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumGameStatusFieldUpdateOperationsInput | $Enums.GameStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ScheduledGameOrderByRelevanceInput = {
  fields: Prisma.ScheduledGameOrderByRelevanceFieldEnum | Prisma.ScheduledGameOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ScheduledGameCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  category?: Prisma.SortOrder
  homeTeam?: Prisma.SortOrder
  awayTeam?: Prisma.SortOrder
  ballPark?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ScheduledGameMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  category?: Prisma.SortOrder
  homeTeam?: Prisma.SortOrder
  awayTeam?: Prisma.SortOrder
  ballPark?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ScheduledGameMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  category?: Prisma.SortOrder
  homeTeam?: Prisma.SortOrder
  awayTeam?: Prisma.SortOrder
  ballPark?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type EnumGameStatusFieldUpdateOperationsInput = {
  set?: $Enums.GameStatus
}



export type ScheduledGameSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  category?: boolean
  homeTeam?: boolean
  awayTeam?: boolean
  ballPark?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["scheduledGame"]>



export type ScheduledGameSelectScalar = {
  id?: boolean
  date?: boolean
  category?: boolean
  homeTeam?: boolean
  awayTeam?: boolean
  ballPark?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ScheduledGameOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "category" | "homeTeam" | "awayTeam" | "ballPark" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["scheduledGame"]>

export type $ScheduledGamePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ScheduledGame"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    date: Date
    category: string
    homeTeam: string
    awayTeam: string
    ballPark: string
    status: $Enums.GameStatus
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["scheduledGame"]>
  composites: {}
}

export type ScheduledGameGetPayload<S extends boolean | null | undefined | ScheduledGameDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ScheduledGamePayload, S>

export type ScheduledGameCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ScheduledGameFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ScheduledGameCountAggregateInputType | true
  }

export interface ScheduledGameDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ScheduledGame'], meta: { name: 'ScheduledGame' } }
  /**
   * Find zero or one ScheduledGame that matches the filter.
   * @param {ScheduledGameFindUniqueArgs} args - Arguments to find a ScheduledGame
   * @example
   * // Get one ScheduledGame
   * const scheduledGame = await prisma.scheduledGame.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ScheduledGameFindUniqueArgs>(args: Prisma.SelectSubset<T, ScheduledGameFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ScheduledGameClient<runtime.Types.Result.GetResult<Prisma.$ScheduledGamePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ScheduledGame that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ScheduledGameFindUniqueOrThrowArgs} args - Arguments to find a ScheduledGame
   * @example
   * // Get one ScheduledGame
   * const scheduledGame = await prisma.scheduledGame.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ScheduledGameFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ScheduledGameFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ScheduledGameClient<runtime.Types.Result.GetResult<Prisma.$ScheduledGamePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ScheduledGame that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledGameFindFirstArgs} args - Arguments to find a ScheduledGame
   * @example
   * // Get one ScheduledGame
   * const scheduledGame = await prisma.scheduledGame.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ScheduledGameFindFirstArgs>(args?: Prisma.SelectSubset<T, ScheduledGameFindFirstArgs<ExtArgs>>): Prisma.Prisma__ScheduledGameClient<runtime.Types.Result.GetResult<Prisma.$ScheduledGamePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ScheduledGame that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledGameFindFirstOrThrowArgs} args - Arguments to find a ScheduledGame
   * @example
   * // Get one ScheduledGame
   * const scheduledGame = await prisma.scheduledGame.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ScheduledGameFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ScheduledGameFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ScheduledGameClient<runtime.Types.Result.GetResult<Prisma.$ScheduledGamePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ScheduledGames that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledGameFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ScheduledGames
   * const scheduledGames = await prisma.scheduledGame.findMany()
   * 
   * // Get first 10 ScheduledGames
   * const scheduledGames = await prisma.scheduledGame.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const scheduledGameWithIdOnly = await prisma.scheduledGame.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ScheduledGameFindManyArgs>(args?: Prisma.SelectSubset<T, ScheduledGameFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ScheduledGamePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ScheduledGame.
   * @param {ScheduledGameCreateArgs} args - Arguments to create a ScheduledGame.
   * @example
   * // Create one ScheduledGame
   * const ScheduledGame = await prisma.scheduledGame.create({
   *   data: {
   *     // ... data to create a ScheduledGame
   *   }
   * })
   * 
   */
  create<T extends ScheduledGameCreateArgs>(args: Prisma.SelectSubset<T, ScheduledGameCreateArgs<ExtArgs>>): Prisma.Prisma__ScheduledGameClient<runtime.Types.Result.GetResult<Prisma.$ScheduledGamePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ScheduledGames.
   * @param {ScheduledGameCreateManyArgs} args - Arguments to create many ScheduledGames.
   * @example
   * // Create many ScheduledGames
   * const scheduledGame = await prisma.scheduledGame.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ScheduledGameCreateManyArgs>(args?: Prisma.SelectSubset<T, ScheduledGameCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ScheduledGame.
   * @param {ScheduledGameDeleteArgs} args - Arguments to delete one ScheduledGame.
   * @example
   * // Delete one ScheduledGame
   * const ScheduledGame = await prisma.scheduledGame.delete({
   *   where: {
   *     // ... filter to delete one ScheduledGame
   *   }
   * })
   * 
   */
  delete<T extends ScheduledGameDeleteArgs>(args: Prisma.SelectSubset<T, ScheduledGameDeleteArgs<ExtArgs>>): Prisma.Prisma__ScheduledGameClient<runtime.Types.Result.GetResult<Prisma.$ScheduledGamePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ScheduledGame.
   * @param {ScheduledGameUpdateArgs} args - Arguments to update one ScheduledGame.
   * @example
   * // Update one ScheduledGame
   * const scheduledGame = await prisma.scheduledGame.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ScheduledGameUpdateArgs>(args: Prisma.SelectSubset<T, ScheduledGameUpdateArgs<ExtArgs>>): Prisma.Prisma__ScheduledGameClient<runtime.Types.Result.GetResult<Prisma.$ScheduledGamePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ScheduledGames.
   * @param {ScheduledGameDeleteManyArgs} args - Arguments to filter ScheduledGames to delete.
   * @example
   * // Delete a few ScheduledGames
   * const { count } = await prisma.scheduledGame.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ScheduledGameDeleteManyArgs>(args?: Prisma.SelectSubset<T, ScheduledGameDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ScheduledGames.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledGameUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ScheduledGames
   * const scheduledGame = await prisma.scheduledGame.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ScheduledGameUpdateManyArgs>(args: Prisma.SelectSubset<T, ScheduledGameUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ScheduledGame.
   * @param {ScheduledGameUpsertArgs} args - Arguments to update or create a ScheduledGame.
   * @example
   * // Update or create a ScheduledGame
   * const scheduledGame = await prisma.scheduledGame.upsert({
   *   create: {
   *     // ... data to create a ScheduledGame
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ScheduledGame we want to update
   *   }
   * })
   */
  upsert<T extends ScheduledGameUpsertArgs>(args: Prisma.SelectSubset<T, ScheduledGameUpsertArgs<ExtArgs>>): Prisma.Prisma__ScheduledGameClient<runtime.Types.Result.GetResult<Prisma.$ScheduledGamePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ScheduledGames.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledGameCountArgs} args - Arguments to filter ScheduledGames to count.
   * @example
   * // Count the number of ScheduledGames
   * const count = await prisma.scheduledGame.count({
   *   where: {
   *     // ... the filter for the ScheduledGames we want to count
   *   }
   * })
  **/
  count<T extends ScheduledGameCountArgs>(
    args?: Prisma.Subset<T, ScheduledGameCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ScheduledGameCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ScheduledGame.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledGameAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ScheduledGameAggregateArgs>(args: Prisma.Subset<T, ScheduledGameAggregateArgs>): Prisma.PrismaPromise<GetScheduledGameAggregateType<T>>

  /**
   * Group by ScheduledGame.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledGameGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ScheduledGameGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ScheduledGameGroupByArgs['orderBy'] }
      : { orderBy?: ScheduledGameGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ScheduledGameGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetScheduledGameGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ScheduledGame model
 */
readonly fields: ScheduledGameFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ScheduledGame.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ScheduledGameClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ScheduledGame model
 */
export interface ScheduledGameFieldRefs {
  readonly id: Prisma.FieldRef<"ScheduledGame", 'String'>
  readonly date: Prisma.FieldRef<"ScheduledGame", 'DateTime'>
  readonly category: Prisma.FieldRef<"ScheduledGame", 'String'>
  readonly homeTeam: Prisma.FieldRef<"ScheduledGame", 'String'>
  readonly awayTeam: Prisma.FieldRef<"ScheduledGame", 'String'>
  readonly ballPark: Prisma.FieldRef<"ScheduledGame", 'String'>
  readonly status: Prisma.FieldRef<"ScheduledGame", 'GameStatus'>
  readonly createdAt: Prisma.FieldRef<"ScheduledGame", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ScheduledGame", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ScheduledGame findUnique
 */
export type ScheduledGameFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledGame
   */
  select?: Prisma.ScheduledGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledGame
   */
  omit?: Prisma.ScheduledGameOmit<ExtArgs> | null
  /**
   * Filter, which ScheduledGame to fetch.
   */
  where: Prisma.ScheduledGameWhereUniqueInput
}

/**
 * ScheduledGame findUniqueOrThrow
 */
export type ScheduledGameFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledGame
   */
  select?: Prisma.ScheduledGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledGame
   */
  omit?: Prisma.ScheduledGameOmit<ExtArgs> | null
  /**
   * Filter, which ScheduledGame to fetch.
   */
  where: Prisma.ScheduledGameWhereUniqueInput
}

/**
 * ScheduledGame findFirst
 */
export type ScheduledGameFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledGame
   */
  select?: Prisma.ScheduledGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledGame
   */
  omit?: Prisma.ScheduledGameOmit<ExtArgs> | null
  /**
   * Filter, which ScheduledGame to fetch.
   */
  where?: Prisma.ScheduledGameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ScheduledGames to fetch.
   */
  orderBy?: Prisma.ScheduledGameOrderByWithRelationInput | Prisma.ScheduledGameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ScheduledGames.
   */
  cursor?: Prisma.ScheduledGameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ScheduledGames from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ScheduledGames.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ScheduledGames.
   */
  distinct?: Prisma.ScheduledGameScalarFieldEnum | Prisma.ScheduledGameScalarFieldEnum[]
}

/**
 * ScheduledGame findFirstOrThrow
 */
export type ScheduledGameFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledGame
   */
  select?: Prisma.ScheduledGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledGame
   */
  omit?: Prisma.ScheduledGameOmit<ExtArgs> | null
  /**
   * Filter, which ScheduledGame to fetch.
   */
  where?: Prisma.ScheduledGameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ScheduledGames to fetch.
   */
  orderBy?: Prisma.ScheduledGameOrderByWithRelationInput | Prisma.ScheduledGameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ScheduledGames.
   */
  cursor?: Prisma.ScheduledGameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ScheduledGames from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ScheduledGames.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ScheduledGames.
   */
  distinct?: Prisma.ScheduledGameScalarFieldEnum | Prisma.ScheduledGameScalarFieldEnum[]
}

/**
 * ScheduledGame findMany
 */
export type ScheduledGameFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledGame
   */
  select?: Prisma.ScheduledGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledGame
   */
  omit?: Prisma.ScheduledGameOmit<ExtArgs> | null
  /**
   * Filter, which ScheduledGames to fetch.
   */
  where?: Prisma.ScheduledGameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ScheduledGames to fetch.
   */
  orderBy?: Prisma.ScheduledGameOrderByWithRelationInput | Prisma.ScheduledGameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ScheduledGames.
   */
  cursor?: Prisma.ScheduledGameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ScheduledGames from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ScheduledGames.
   */
  skip?: number
  distinct?: Prisma.ScheduledGameScalarFieldEnum | Prisma.ScheduledGameScalarFieldEnum[]
}

/**
 * ScheduledGame create
 */
export type ScheduledGameCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledGame
   */
  select?: Prisma.ScheduledGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledGame
   */
  omit?: Prisma.ScheduledGameOmit<ExtArgs> | null
  /**
   * The data needed to create a ScheduledGame.
   */
  data: Prisma.XOR<Prisma.ScheduledGameCreateInput, Prisma.ScheduledGameUncheckedCreateInput>
}

/**
 * ScheduledGame createMany
 */
export type ScheduledGameCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ScheduledGames.
   */
  data: Prisma.ScheduledGameCreateManyInput | Prisma.ScheduledGameCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ScheduledGame update
 */
export type ScheduledGameUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledGame
   */
  select?: Prisma.ScheduledGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledGame
   */
  omit?: Prisma.ScheduledGameOmit<ExtArgs> | null
  /**
   * The data needed to update a ScheduledGame.
   */
  data: Prisma.XOR<Prisma.ScheduledGameUpdateInput, Prisma.ScheduledGameUncheckedUpdateInput>
  /**
   * Choose, which ScheduledGame to update.
   */
  where: Prisma.ScheduledGameWhereUniqueInput
}

/**
 * ScheduledGame updateMany
 */
export type ScheduledGameUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ScheduledGames.
   */
  data: Prisma.XOR<Prisma.ScheduledGameUpdateManyMutationInput, Prisma.ScheduledGameUncheckedUpdateManyInput>
  /**
   * Filter which ScheduledGames to update
   */
  where?: Prisma.ScheduledGameWhereInput
  /**
   * Limit how many ScheduledGames to update.
   */
  limit?: number
}

/**
 * ScheduledGame upsert
 */
export type ScheduledGameUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledGame
   */
  select?: Prisma.ScheduledGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledGame
   */
  omit?: Prisma.ScheduledGameOmit<ExtArgs> | null
  /**
   * The filter to search for the ScheduledGame to update in case it exists.
   */
  where: Prisma.ScheduledGameWhereUniqueInput
  /**
   * In case the ScheduledGame found by the `where` argument doesn't exist, create a new ScheduledGame with this data.
   */
  create: Prisma.XOR<Prisma.ScheduledGameCreateInput, Prisma.ScheduledGameUncheckedCreateInput>
  /**
   * In case the ScheduledGame was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ScheduledGameUpdateInput, Prisma.ScheduledGameUncheckedUpdateInput>
}

/**
 * ScheduledGame delete
 */
export type ScheduledGameDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledGame
   */
  select?: Prisma.ScheduledGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledGame
   */
  omit?: Prisma.ScheduledGameOmit<ExtArgs> | null
  /**
   * Filter which ScheduledGame to delete.
   */
  where: Prisma.ScheduledGameWhereUniqueInput
}

/**
 * ScheduledGame deleteMany
 */
export type ScheduledGameDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ScheduledGames to delete
   */
  where?: Prisma.ScheduledGameWhereInput
  /**
   * Limit how many ScheduledGames to delete.
   */
  limit?: number
}

/**
 * ScheduledGame without action
 */
export type ScheduledGameDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ScheduledGame
   */
  select?: Prisma.ScheduledGameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledGame
   */
  omit?: Prisma.ScheduledGameOmit<ExtArgs> | null
}
