
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model ScheduledGame
 * 
 */
export type ScheduledGame = Prisma.ScheduledGameModel
/**
 * Model PastGameRecord
 * 
 */
export type PastGameRecord = Prisma.PastGameRecordModel
/**
 * Model BallParkHourlyWeatherForecast
 * 
 */
export type BallParkHourlyWeatherForecast = Prisma.BallParkHourlyWeatherForecastModel
/**
 * Model BallParkDailyWeatherForecast
 * 
 */
export type BallParkDailyWeatherForecast = Prisma.BallParkDailyWeatherForecastModel
/**
 * Model BallParkObservedHourlyWeather
 * 
 */
export type BallParkObservedHourlyWeather = Prisma.BallParkObservedHourlyWeatherModel
/**
 * Model CancellationModel
 * 
 */
export type CancellationModel = Prisma.CancellationModelModel
