
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.ts"
import * as $Class from "./internal/class.ts"
import * as Prisma from "./internal/prismaNamespace.ts"

export * as $Enums from './enums.ts'
export * from "./enums.ts"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more ScheduledGames
 * const scheduledGames = await prisma.scheduledGame.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model ScheduledGame
 * 
 */
export type ScheduledGame = Prisma.ScheduledGameModel
/**
 * Model PastGameRecord
 * 
 */
export type PastGameRecord = Prisma.PastGameRecordModel
/**
 * Model BallParkHourlyWeatherForecast
 * 
 */
export type BallParkHourlyWeatherForecast = Prisma.BallParkHourlyWeatherForecastModel
/**
 * Model BallParkDailyWeatherForecast
 * 
 */
export type BallParkDailyWeatherForecast = Prisma.BallParkDailyWeatherForecastModel
/**
 * Model BallParkObservedHourlyWeather
 * 
 */
export type BallParkObservedHourlyWeather = Prisma.BallParkObservedHourlyWeatherModel
