
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  ScheduledGame: 'ScheduledGame',
  PastGameRecord: 'PastGameRecord',
  BallParkHourlyWeatherForecast: 'BallParkHourlyWeatherForecast',
  BallParkDailyWeatherForecast: 'BallParkDailyWeatherForecast',
  BallParkObservedHourlyWeather: 'BallParkObservedHourlyWeather'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ScheduledGameScalarFieldEnum = {
  id: 'id',
  date: 'date',
  category: 'category',
  homeTeam: 'homeTeam',
  awayTeam: 'awayTeam',
  ballPark: 'ballPark',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ScheduledGameScalarFieldEnum = (typeof ScheduledGameScalarFieldEnum)[keyof typeof ScheduledGameScalarFieldEnum]


export const PastGameRecordScalarFieldEnum = {
  id: 'id',
  date: 'date',
  homeTeam: 'homeTeam',
  awayTeam: 'awayTeam',
  ballPark: 'ballPark',
  cancelled: 'cancelled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PastGameRecordScalarFieldEnum = (typeof PastGameRecordScalarFieldEnum)[keyof typeof PastGameRecordScalarFieldEnum]


export const BallParkHourlyWeatherForecastScalarFieldEnum = {
  id: 'id',
  date: 'date',
  weatherCode: 'weatherCode',
  temperature: 'temperature',
  precipitationProbability: 'precipitationProbability',
  rainFall: 'rainFall',
  ballParkId: 'ballParkId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BallParkHourlyWeatherForecastScalarFieldEnum = (typeof BallParkHourlyWeatherForecastScalarFieldEnum)[keyof typeof BallParkHourlyWeatherForecastScalarFieldEnum]


export const BallParkDailyWeatherForecastScalarFieldEnum = {
  id: 'id',
  date: 'date',
  weatherCode: 'weatherCode',
  temperatureMin: 'temperatureMin',
  temperatureMax: 'temperatureMax',
  precipitationProbability: 'precipitationProbability',
  rainFall: 'rainFall',
  ballParkId: 'ballParkId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BallParkDailyWeatherForecastScalarFieldEnum = (typeof BallParkDailyWeatherForecastScalarFieldEnum)[keyof typeof BallParkDailyWeatherForecastScalarFieldEnum]


export const BallParkObservedHourlyWeatherScalarFieldEnum = {
  id: 'id',
  date: 'date',
  temperature: 'temperature',
  rainfallOccurred: 'rainfallOccurred',
  rainFall: 'rainFall',
  ballParkId: 'ballParkId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BallParkObservedHourlyWeatherScalarFieldEnum = (typeof BallParkObservedHourlyWeatherScalarFieldEnum)[keyof typeof BallParkObservedHourlyWeatherScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const ScheduledGameOrderByRelevanceFieldEnum = {
  id: 'id',
  category: 'category',
  homeTeam: 'homeTeam',
  awayTeam: 'awayTeam',
  ballPark: 'ballPark'
} as const

export type ScheduledGameOrderByRelevanceFieldEnum = (typeof ScheduledGameOrderByRelevanceFieldEnum)[keyof typeof ScheduledGameOrderByRelevanceFieldEnum]


export const PastGameRecordOrderByRelevanceFieldEnum = {
  homeTeam: 'homeTeam',
  awayTeam: 'awayTeam',
  ballPark: 'ballPark'
} as const

export type PastGameRecordOrderByRelevanceFieldEnum = (typeof PastGameRecordOrderByRelevanceFieldEnum)[keyof typeof PastGameRecordOrderByRelevanceFieldEnum]

