
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.ts"
import { type PrismaClient } from "./class.ts"

export type * from '../models.ts'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.2.0
 * Query Engine version: 0c8ef2ce45c83248ab3df073180d5eda9e8be7a3
 */
export const prismaVersion: PrismaVersion = {
  client: "7.2.0",
  engine: "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  ScheduledGame: 'ScheduledGame',
  PastGameRecord: 'PastGameRecord',
  BallParkHourlyWeatherForecast: 'BallParkHourlyWeatherForecast',
  BallParkDailyWeatherForecast: 'BallParkDailyWeatherForecast',
  BallParkObservedHourlyWeather: 'BallParkObservedHourlyWeather',
  CancellationModel: 'CancellationModel'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "scheduledGame" | "pastGameRecord" | "ballParkHourlyWeatherForecast" | "ballParkDailyWeatherForecast" | "ballParkObservedHourlyWeather" | "cancellationModel"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    ScheduledGame: {
      payload: Prisma.$ScheduledGamePayload<ExtArgs>
      fields: Prisma.ScheduledGameFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ScheduledGameFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ScheduledGamePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ScheduledGameFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ScheduledGamePayload>
        }
        findFirst: {
          args: Prisma.ScheduledGameFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ScheduledGamePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ScheduledGameFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ScheduledGamePayload>
        }
        findMany: {
          args: Prisma.ScheduledGameFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ScheduledGamePayload>[]
        }
        create: {
          args: Prisma.ScheduledGameCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ScheduledGamePayload>
        }
        createMany: {
          args: Prisma.ScheduledGameCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.ScheduledGameDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ScheduledGamePayload>
        }
        update: {
          args: Prisma.ScheduledGameUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ScheduledGamePayload>
        }
        deleteMany: {
          args: Prisma.ScheduledGameDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ScheduledGameUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.ScheduledGameUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ScheduledGamePayload>
        }
        aggregate: {
          args: Prisma.ScheduledGameAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateScheduledGame>
        }
        groupBy: {
          args: Prisma.ScheduledGameGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ScheduledGameGroupByOutputType>[]
        }
        count: {
          args: Prisma.ScheduledGameCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ScheduledGameCountAggregateOutputType> | number
        }
      }
    }
    PastGameRecord: {
      payload: Prisma.$PastGameRecordPayload<ExtArgs>
      fields: Prisma.PastGameRecordFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PastGameRecordFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PastGameRecordPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PastGameRecordFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PastGameRecordPayload>
        }
        findFirst: {
          args: Prisma.PastGameRecordFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PastGameRecordPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PastGameRecordFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PastGameRecordPayload>
        }
        findMany: {
          args: Prisma.PastGameRecordFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PastGameRecordPayload>[]
        }
        create: {
          args: Prisma.PastGameRecordCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PastGameRecordPayload>
        }
        createMany: {
          args: Prisma.PastGameRecordCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.PastGameRecordDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PastGameRecordPayload>
        }
        update: {
          args: Prisma.PastGameRecordUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PastGameRecordPayload>
        }
        deleteMany: {
          args: Prisma.PastGameRecordDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PastGameRecordUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.PastGameRecordUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PastGameRecordPayload>
        }
        aggregate: {
          args: Prisma.PastGameRecordAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePastGameRecord>
        }
        groupBy: {
          args: Prisma.PastGameRecordGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PastGameRecordGroupByOutputType>[]
        }
        count: {
          args: Prisma.PastGameRecordCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PastGameRecordCountAggregateOutputType> | number
        }
      }
    }
    BallParkHourlyWeatherForecast: {
      payload: Prisma.$BallParkHourlyWeatherForecastPayload<ExtArgs>
      fields: Prisma.BallParkHourlyWeatherForecastFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BallParkHourlyWeatherForecastFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkHourlyWeatherForecastPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BallParkHourlyWeatherForecastFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkHourlyWeatherForecastPayload>
        }
        findFirst: {
          args: Prisma.BallParkHourlyWeatherForecastFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkHourlyWeatherForecastPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BallParkHourlyWeatherForecastFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkHourlyWeatherForecastPayload>
        }
        findMany: {
          args: Prisma.BallParkHourlyWeatherForecastFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkHourlyWeatherForecastPayload>[]
        }
        create: {
          args: Prisma.BallParkHourlyWeatherForecastCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkHourlyWeatherForecastPayload>
        }
        createMany: {
          args: Prisma.BallParkHourlyWeatherForecastCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.BallParkHourlyWeatherForecastDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkHourlyWeatherForecastPayload>
        }
        update: {
          args: Prisma.BallParkHourlyWeatherForecastUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkHourlyWeatherForecastPayload>
        }
        deleteMany: {
          args: Prisma.BallParkHourlyWeatherForecastDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BallParkHourlyWeatherForecastUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.BallParkHourlyWeatherForecastUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkHourlyWeatherForecastPayload>
        }
        aggregate: {
          args: Prisma.BallParkHourlyWeatherForecastAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBallParkHourlyWeatherForecast>
        }
        groupBy: {
          args: Prisma.BallParkHourlyWeatherForecastGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BallParkHourlyWeatherForecastGroupByOutputType>[]
        }
        count: {
          args: Prisma.BallParkHourlyWeatherForecastCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BallParkHourlyWeatherForecastCountAggregateOutputType> | number
        }
      }
    }
    BallParkDailyWeatherForecast: {
      payload: Prisma.$BallParkDailyWeatherForecastPayload<ExtArgs>
      fields: Prisma.BallParkDailyWeatherForecastFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BallParkDailyWeatherForecastFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkDailyWeatherForecastPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BallParkDailyWeatherForecastFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkDailyWeatherForecastPayload>
        }
        findFirst: {
          args: Prisma.BallParkDailyWeatherForecastFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkDailyWeatherForecastPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BallParkDailyWeatherForecastFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkDailyWeatherForecastPayload>
        }
        findMany: {
          args: Prisma.BallParkDailyWeatherForecastFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkDailyWeatherForecastPayload>[]
        }
        create: {
          args: Prisma.BallParkDailyWeatherForecastCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkDailyWeatherForecastPayload>
        }
        createMany: {
          args: Prisma.BallParkDailyWeatherForecastCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.BallParkDailyWeatherForecastDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkDailyWeatherForecastPayload>
        }
        update: {
          args: Prisma.BallParkDailyWeatherForecastUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkDailyWeatherForecastPayload>
        }
        deleteMany: {
          args: Prisma.BallParkDailyWeatherForecastDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BallParkDailyWeatherForecastUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.BallParkDailyWeatherForecastUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkDailyWeatherForecastPayload>
        }
        aggregate: {
          args: Prisma.BallParkDailyWeatherForecastAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBallParkDailyWeatherForecast>
        }
        groupBy: {
          args: Prisma.BallParkDailyWeatherForecastGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BallParkDailyWeatherForecastGroupByOutputType>[]
        }
        count: {
          args: Prisma.BallParkDailyWeatherForecastCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BallParkDailyWeatherForecastCountAggregateOutputType> | number
        }
      }
    }
    BallParkObservedHourlyWeather: {
      payload: Prisma.$BallParkObservedHourlyWeatherPayload<ExtArgs>
      fields: Prisma.BallParkObservedHourlyWeatherFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BallParkObservedHourlyWeatherFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkObservedHourlyWeatherPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BallParkObservedHourlyWeatherFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkObservedHourlyWeatherPayload>
        }
        findFirst: {
          args: Prisma.BallParkObservedHourlyWeatherFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkObservedHourlyWeatherPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BallParkObservedHourlyWeatherFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkObservedHourlyWeatherPayload>
        }
        findMany: {
          args: Prisma.BallParkObservedHourlyWeatherFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkObservedHourlyWeatherPayload>[]
        }
        create: {
          args: Prisma.BallParkObservedHourlyWeatherCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkObservedHourlyWeatherPayload>
        }
        createMany: {
          args: Prisma.BallParkObservedHourlyWeatherCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.BallParkObservedHourlyWeatherDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkObservedHourlyWeatherPayload>
        }
        update: {
          args: Prisma.BallParkObservedHourlyWeatherUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkObservedHourlyWeatherPayload>
        }
        deleteMany: {
          args: Prisma.BallParkObservedHourlyWeatherDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BallParkObservedHourlyWeatherUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.BallParkObservedHourlyWeatherUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BallParkObservedHourlyWeatherPayload>
        }
        aggregate: {
          args: Prisma.BallParkObservedHourlyWeatherAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBallParkObservedHourlyWeather>
        }
        groupBy: {
          args: Prisma.BallParkObservedHourlyWeatherGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BallParkObservedHourlyWeatherGroupByOutputType>[]
        }
        count: {
          args: Prisma.BallParkObservedHourlyWeatherCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BallParkObservedHourlyWeatherCountAggregateOutputType> | number
        }
      }
    }
    CancellationModel: {
      payload: Prisma.$CancellationModelPayload<ExtArgs>
      fields: Prisma.CancellationModelFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CancellationModelFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CancellationModelPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CancellationModelFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CancellationModelPayload>
        }
        findFirst: {
          args: Prisma.CancellationModelFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CancellationModelPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CancellationModelFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CancellationModelPayload>
        }
        findMany: {
          args: Prisma.CancellationModelFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CancellationModelPayload>[]
        }
        create: {
          args: Prisma.CancellationModelCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CancellationModelPayload>
        }
        createMany: {
          args: Prisma.CancellationModelCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.CancellationModelDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CancellationModelPayload>
        }
        update: {
          args: Prisma.CancellationModelUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CancellationModelPayload>
        }
        deleteMany: {
          args: Prisma.CancellationModelDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CancellationModelUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.CancellationModelUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CancellationModelPayload>
        }
        aggregate: {
          args: Prisma.CancellationModelAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCancellationModel>
        }
        groupBy: {
          args: Prisma.CancellationModelGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CancellationModelGroupByOutputType>[]
        }
        count: {
          args: Prisma.CancellationModelCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CancellationModelCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ScheduledGameScalarFieldEnum = {
  id: 'id',
  date: 'date',
  category: 'category',
  homeTeam: 'homeTeam',
  awayTeam: 'awayTeam',
  ballPark: 'ballPark',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ScheduledGameScalarFieldEnum = (typeof ScheduledGameScalarFieldEnum)[keyof typeof ScheduledGameScalarFieldEnum]


export const PastGameRecordScalarFieldEnum = {
  id: 'id',
  date: 'date',
  homeTeam: 'homeTeam',
  awayTeam: 'awayTeam',
  ballPark: 'ballPark',
  cancelled: 'cancelled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PastGameRecordScalarFieldEnum = (typeof PastGameRecordScalarFieldEnum)[keyof typeof PastGameRecordScalarFieldEnum]


export const BallParkHourlyWeatherForecastScalarFieldEnum = {
  id: 'id',
  date: 'date',
  weatherCode: 'weatherCode',
  temperature: 'temperature',
  precipitationProbability: 'precipitationProbability',
  rainFall: 'rainFall',
  ballParkId: 'ballParkId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BallParkHourlyWeatherForecastScalarFieldEnum = (typeof BallParkHourlyWeatherForecastScalarFieldEnum)[keyof typeof BallParkHourlyWeatherForecastScalarFieldEnum]


export const BallParkDailyWeatherForecastScalarFieldEnum = {
  id: 'id',
  date: 'date',
  weatherCode: 'weatherCode',
  temperatureMin: 'temperatureMin',
  temperatureMax: 'temperatureMax',
  precipitationProbability: 'precipitationProbability',
  rainFall: 'rainFall',
  ballParkId: 'ballParkId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BallParkDailyWeatherForecastScalarFieldEnum = (typeof BallParkDailyWeatherForecastScalarFieldEnum)[keyof typeof BallParkDailyWeatherForecastScalarFieldEnum]


export const BallParkObservedHourlyWeatherScalarFieldEnum = {
  id: 'id',
  date: 'date',
  temperature: 'temperature',
  rainfallOccurred: 'rainfallOccurred',
  rainFall: 'rainFall',
  ballParkId: 'ballParkId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BallParkObservedHourlyWeatherScalarFieldEnum = (typeof BallParkObservedHourlyWeatherScalarFieldEnum)[keyof typeof BallParkObservedHourlyWeatherScalarFieldEnum]


export const CancellationModelScalarFieldEnum = {
  id: 'id',
  version: 'version',
  featureOrder: 'featureOrder',
  coefficients: 'coefficients',
  intercept: 'intercept',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CancellationModelScalarFieldEnum = (typeof CancellationModelScalarFieldEnum)[keyof typeof CancellationModelScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const ScheduledGameOrderByRelevanceFieldEnum = {
  id: 'id',
  category: 'category',
  homeTeam: 'homeTeam',
  awayTeam: 'awayTeam',
  ballPark: 'ballPark'
} as const

export type ScheduledGameOrderByRelevanceFieldEnum = (typeof ScheduledGameOrderByRelevanceFieldEnum)[keyof typeof ScheduledGameOrderByRelevanceFieldEnum]


export const PastGameRecordOrderByRelevanceFieldEnum = {
  homeTeam: 'homeTeam',
  awayTeam: 'awayTeam',
  ballPark: 'ballPark'
} as const

export type PastGameRecordOrderByRelevanceFieldEnum = (typeof PastGameRecordOrderByRelevanceFieldEnum)[keyof typeof PastGameRecordOrderByRelevanceFieldEnum]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const CancellationModelOrderByRelevanceFieldEnum = {
  id: 'id',
  version: 'version'
} as const

export type CancellationModelOrderByRelevanceFieldEnum = (typeof CancellationModelOrderByRelevanceFieldEnum)[keyof typeof CancellationModelOrderByRelevanceFieldEnum]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'GameStatus'
 */
export type EnumGameStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'GameStatus'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  scheduledGame?: Prisma.ScheduledGameOmit
  pastGameRecord?: Prisma.PastGameRecordOmit
  ballParkHourlyWeatherForecast?: Prisma.BallParkHourlyWeatherForecastOmit
  ballParkDailyWeatherForecast?: Prisma.BallParkDailyWeatherForecastOmit
  ballParkObservedHourlyWeather?: Prisma.BallParkObservedHourlyWeatherOmit
  cancellationModel?: Prisma.CancellationModelOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

