import { promises as fs } from "node:fs";
import path from "node:path";
import subsetFont from "subset-font";

// ★ 置いてくれた元フォントのパスに合わせて変更してください
const FONT_SRC = path.resolve(
  process.cwd(),
  "scripts/_fonts/NotoSansJP-Bold.ttf",
);
const OUTPUT = path.resolve(process.cwd(), "src/generated/ogFont.generated.ts");

// OGで出る固定文言（opengraph-image.tsx と一致させる）
const FIXED_TEXTS = [
  "プロ野球 雨天中止予報",
  "今日の天気は",
  "今日は試合がないので",
  "本日の試合の雨天中止予測をチェック！",
  "明日以降の試合情報と天気をチェック！",
  "天気情報更新中",
  "の",
  "中止確率", // ← #B（中止確率表示）を見据えて先に含めておく
  // OG 中止確率表示の確定文言（メイン/サブ）
  "今日の試合の中止予測は",
  "中止確率は定期的に変わります。こまめに確認を！",
  // OG フォールバック（ケース別）の確定文言
  "今日はドーム開催！",
  "の試合は",
  "雨天中止の心配なし！",
  "中止予測はまもなく公開",
  "本日の試合の予測を準備中です",
  "今日の試合をチェック！",
  "試合情報と天気をチェック！",
];

// 12チームの正式名称（team.ts と一致）
const TEAM_FULL_NAMES = [
  "東京ヤクルトスワローズ",
  "読売ジャイアンツ",
  "阪神タイガース",
  "広島東洋カープ",
  "中日ドラゴンズ",
  "横浜DeNAベイスターズ",
  "北海道日本ハムファイターズ",
  "千葉ロッテマリーンズ",
  "オリックスバファローズ",
  "埼玉西武ライオンズ",
  "福岡ソフトバンクホークス",
  "東北楽天ゴールデンイーグルス",
];

// 天気ラベル（WeatherCodeCatalog の labelJa 全部）
const WEATHER_LABELS = [
  "晴れ",
  "主に晴れ",
  "一部曇り",
  "曇り",
  "霧",
  "霧氷",
  "軽い霧雨",
  "霧雨",
  "強い霧雨",
  "軽い着氷霧雨",
  "着氷霧雨",
  "弱い雨",
  "中程度の雨",
  "強い雨",
  "軽い着氷雨",
  "着氷雨",
  // …WeatherCodeCatalog に載っている残りの labelJa も全部ここに列挙
];

// 数字・記号・日付関連
const SYMBOLS = "0123456789/％%！ 　年月日()（）℃.-";

function buildCharSet(): string {
  const all = [
    ...FIXED_TEXTS,
    ...TEAM_FULL_NAMES,
    ...WEATHER_LABELS,
    SYMBOLS,
  ].join("");

  // 安全マージン: ひらがな・カタカナ全域も足しておく（数KB程度、将来の文言変更に強い）
  let kana = "";
  for (let c = 0x3041; c <= 0x3096; c++) kana += String.fromCodePoint(c); // ひらがな
  for (let c = 0x30a1; c <= 0x30fc; c++) kana += String.fromCodePoint(c); // カタカナ+長音

  // 重複除去
  return Array.from(new Set((all + kana).split(""))).join("");
}

async function main() {
  const src = await fs.readFile(FONT_SRC);
  const chars = buildCharSet();

  // ★ satori 対応のため woff（または ttf）で出力。woff2 はNG
  const subset = await subsetFont(src, chars, { targetFormat: "woff" });

  const base64 = subset.toString("base64");
  const out = `// AUTO-GENERATED by scripts/generateOgFont.ts. Do not edit.
export const OG_FONT_BASE64 = ${JSON.stringify(base64)};
`;
  await fs.mkdir(path.dirname(OUTPUT), { recursive: true });
  await fs.writeFile(OUTPUT, out, "utf8");
  console.log(
    `Generated OG font subset: ${chars.length} glyphs, ${(subset.length / 1024).toFixed(1)}KB`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
