import { promises as fs } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const PUBLIC = path.resolve(process.cwd(), "public");
const OUTPUT = path.resolve(
  process.cwd(),
  "src/generated/ogAssets.generated.ts",
);

async function toDataUri(
  absPath: string,
  resize?: { width: number; height?: number; fit: "cover" | "inside" },
): Promise<string> {
  let img = sharp(absPath);
  if (resize) {
    img = img.resize({
      width: resize.width,
      height: resize.height,
      fit: resize.fit,
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    });
  }
  const ext = path.extname(absPath).toLowerCase();
  // satori は png/jpeg のみ対応。jpg はそのまま、それ以外は png 化。
  const isJpeg = ext === ".jpg" || ext === ".jpeg";
  const buf = isJpeg
    ? await img.jpeg({ quality: 82 }).toBuffer()
    : await img.png().toBuffer();
  const mime = isJpeg ? "image/jpeg" : "image/png";
  return `data:${mime};base64,${buf.toString("base64")}`;
}

async function main() {
  // 背景（常に使用）: OGサイズに固定
  const bg = await toDataUri(path.join(PUBLIC, "og/raindrops.png"), {
    width: 1200,
    height: 630,
    fit: "cover",
  });

  // サイトロゴ（常に使用）: 小さいので軽い
  const siteLogo = await toDataUri(path.join(PUBLIC, "logo/logo.png"), {
    width: 64,
    fit: "inside",
  });

  // チームロゴ 12種: public/teams/*.{png,jpg} を stem(大文字) = TeamId でマップ
  const teamsDir = path.join(PUBLIC, "teams");
  const files = (await fs.readdir(teamsDir)).filter((f) =>
    /\.(png|jpe?g)$/i.test(f),
  );
  const teamLogos: Record<string, string> = {};
  for (const file of files) {
    const teamId = path.basename(file, path.extname(file)).toUpperCase();
    teamLogos[teamId] = await toDataUri(path.join(teamsDir, file), {
      width: 220,
      fit: "inside",
    });
  }

  const out = `// AUTO-GENERATED by scripts/generateOgAssets.ts. Do not edit.
export const OG_BG = ${JSON.stringify(bg)};
export const OG_SITE_LOGO = ${JSON.stringify(siteLogo)};
export const OG_TEAM_LOGOS: Record<string, string> = ${JSON.stringify(
    teamLogos,
  )};
`;

  await fs.mkdir(path.dirname(OUTPUT), { recursive: true });
  await fs.writeFile(OUTPUT, out, "utf8");
  console.log(`Generated OG assets (${Object.keys(teamLogos).length} teams).`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
