// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import path from "path";
import { defineConfig, env } from "prisma/config";
dotenv.config({ path: path.resolve(__dirname, "../.env") });

export default defineConfig({
  schema: "src/infra/persistence/mysql/prisma/schema.prisma",
  migrations: {
    path: "src/infra/persistence/mysql/prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
